input-output-hk/partner-chains

partner-chains-cli/src/config.rs, partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, partner-chains-cli/src/setup_main_chain_state/mod.rs, partner-chains-cli/src/setup_main_chain_state/tests.rs, partner-chains-cli/src/smart_contracts.rs
* ~Display a better error message for Kupo and Ogmios connection error~ removed checks for Kupo and Ogmios connection. it will better be handled by the smart contracts CLI
* Check for existence of `sidechain-main-cli` before running
for you.
=> change: ETCM-8051 setup-main-chain-state checks

partner-chains-cli/src/start_node/mod.rs, runtime/src/mock.rs
Fixing warning when running `cargo test` and `cargo clippy`.
for you.
=> chore: fix 'test' and 'clippy' warnings

changelog.md, mainchain-follower/db-sync-follower/src/block/tests.rs, mainchain-follower/db-sync-follower/src/db_model.rs, mainchain-follower/main-chain-follower-api/src/mock_services.rs, mainchain-follower/mock/src/block.rs, node/src/tests/inherent_data_tests.rs, node/src/tests/runtime_api_mock.rs, primitives/domain/src/lib.rs, primitives/sidechain-mc-hash/src/lib.rs, primitives/sidechain-mc-hash/src/test.rs
Changed the inner type of `McBlockHash` from variable-length `Vec<u8>` to constant length array `[u8; 32]`.
for you.
=> change: change McBlockHash inner type from Vec to an array

node/src/command/mod.rs
Each of command returns `Result<String, String>` but the `print_result` function was failing if result was `Err`. I've introduced this defect recently.
=> bugfix: exit with return code 0 when one of partner chains commands fails

changelog.md, pallets/session-validator-management/src/lib.rs, pallets/session-validator-management/src/mock.rs, pallets/sidechain/src/lib.rs, pallets/sidechain/src/mock.rs, pallets/sidechain/src/tests.rs
See: https://github.com/pari…tytech/polkadot-sdk/issues/223#issue-1865177650
JIRA: ETCM-8126
to the issue.
for you.
=> feat: remove use 'storage::getter' in partner-chains pallets

Cargo.lock, changelog.md, mainchain-follower/db-sync-follower/src/candidates/mod.rs, mainchain-follower/main-chain-follower-api/src/common.rs, partner-chains-cli/src/prepare_configuration/prepare_chain_params.rs, partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, primitives/domain/Cargo.toml, primitives/domain/src/crypto.rs, primitives/domain/src/lib.rs
* moves existing blake2b implementation from main-chain-folower-api to new `crypto` module in domain crate
* `prepare-chain-params` now uses it to calculate the key-hash of governance authority instead of externally calling cardano-cli
for you.
=> change: Calculate key hash without cardano-cli in prepare-chain-params

.envrc, changelog.md, flake.lock, partner-chains-cli/src/config.rs, partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, partner-chains-cli/src/register/register3.rs, partner-chains-cli/src/setup_main_chain_state/mod.rs, partner-chains-cli/src/setup_main_chain_state/tests.rs
New versions of `sidechain-main-cli` expect a new parameter `--network (mainnet | testnet)` to be passed to the commands that access the chain. This PR adds this parameter where necessary, using the network value stored in the chain config.
‼️ I had to pin the partner-chains-smart-contracts version to the commit that added the parameter, since there's no tagged version that contains it yet. Before merging this PR it would probably be good to have a tagged release of PCSC but if that's too much waiting, we can stick to the commit hash.
for you.
=> change: ETCM-7985 pass network parameter to sidechain-main-cli

.github/workflows/nix.yml
Never let a cache being down or unavailable fail a build
for you.
=> Add a --fallback flag to nix devshells ci

mainchain-follower/db-sync-follower/Cargo.toml, mainchain-follower/db-sync-follower/src/db_model.rs, mainchain-follower/db-sync-follower/src/lib.rs, mainchain-follower/db-sync-follower/src/native_token/mod.rs, mainchain-follower/db-sync-follower/src/native_token/tests.rs, mainchain-follower/db-sync-follower/testdata/native-token/migrations/1_create_schema.sql, mainchain-follower/db-sync-follower/testdata/native-token/migrations/2_data.sql, mainchain-follower/main-chain-follower-api/Cargo.toml, mainchain-follower/main-chain-follower-api/src/lib.rs, mainchain-follower/main-chain-follower-api/src/mock_services.rs, mainchain-follower/main-chain-follower-api/src/native_token.rs, mainchain-follower/mock/Cargo.toml, mainchain-follower/mock/src/lib.rs, mainchain-follower/mock/src/native_token.rs, node/Cargo.toml, node/src/main_chain_follower.rs, node/src/tests/mock.rs, primitives/domain/src/lib.rs, utils/byte-string-derivation/src/lib.rs
Data source that provides observability of native token movement _into_ the illiquid supply on the main chain. There is no metadata attached to the tokens moved, so we ovserve the total sum of tokens that went into the illiquid supply since the last mc-hash referenced by our chain.
I wired the data source in the node in this PR, but it is left unused for now. The next PR is [the inherent data provider](https://github.com/input-output-hk/partner-chains/pull/37). You can see the changes from all the PR together in [this draft PR](https://github.com/input-output-hk/partner-chains/pull/22).
You will need to get someone with write privileges.  Please contact IOG Partner Chains developers to do …
=> change: ETCM-7811 native token data source

Cargo.lock, Cargo.toml, node/Cargo.toml, node/src/inherent_data.rs, node/src/tests/inherent_data_tests.rs, node/src/tests/runtime_api_mock.rs, primitives/native-token-management/Cargo.toml, primitives/native-token-management/src/lib.rs, primitives/native-token-management/src/tests/mod.rs, primitives/native-token-management/src/tests/runtime_api_mock.rs, primitives/sidechain-mc-hash/Cargo.toml, primitives/sidechain-mc-hash/src/lib.rs, runtime/Cargo.toml, runtime/src/lib.rs
Adds the inherent data provider that uses the data source from the previous PR and produces inherent data containing the number of tokens moved into the illiquid supply. I wired it into the node already so the inherent data is already produced, but there is no pallet to use it yet. 
The next PR is [the pallet](https://github.com/input-output-hk/partner-chains/pull/36). You can see the changes from all the PR together in [this draft PR](https://github.com/input-output-hk/partner-chains/pull/22). 
for you.
=> change: ETCM-7811 native token inherent data provider

Earthfile
Cargo exhibits subtle differences in behavior when dependencies are vendored locally, which can sometimes lead to failure in CI, where the build suceeds on a developers local machine.
It is by no means obvious that the vendored dependencies are the cause of such breakages when they occur, further adding to the headache.
For simplicity, and to more closely match a developers workflow, we now simply fetch the dependencies, instead of vendoring. This allows us to maintain the benefits of seperating the fetch phase from the build (earthly can skip it if it hasn't changed), without the unexpected breakage.
A `CACHE` serves as a persistent cache mount which remains popullated in between layer changes. This is very helpful for speeding up CI when there are genuine layer updates, since we can, …
=> ci: fix two recurring earthly issues

Cargo.lock, Cargo.toml, changelog.md, devnet/.envrc, node/src/chain_spec.rs, node/src/staging.rs, node/src/template_chain_spec.rs, node/src/testnet.rs, pallets/native-token-management/Cargo.toml, pallets/native-token-management/src/lib.rs, pallets/native-token-management/src/mock.rs, pallets/native-token-management/src/tests.rs, primitives/native-token-management/src/lib.rs, runtime/Cargo.toml, runtime/src/lib.rs, staging/.envrc
The pallet that consumes inherent data about number of tokens moved into illiquid supply on main chain and calls a Partner Chain's custom handler.
This is the last PR of the native token observability. You can see the changes from all the PR together in [this draft PR](https://github.com/input-output-hk/partner-chains/pull/22). 
for you.
=> change: ETCM-7811 native token management pallet

Cargo.lock, Cargo.toml, LICENSE-GPL3-with-classpath-exception, changelog.md, client/consensus/aura/Cargo.toml, client/consensus/aura/README.md, client/consensus/aura/src/import_queue.rs, client/consensus/aura/src/lib.rs, node/Cargo.toml, node/src/inherent_data.rs, node/src/service.rs, primitives/sidechain-mc-hash/Cargo.toml, primitives/sidechain-mc-hash/src/lib.rs, primitives/sidechain-mc-hash/src/test.rs
Moves PC modifications of sc-consensus-aura to this repo, in order to eventually get rid of PC fork of polkadot-sdk.
Added crates still depend on polkadot-sdk sp-consensus-aura and its primitives. Only modified code and necessary private functions were moved from our fork.
Based on partnerchains-stable-2407-1 with Aura modifications reverted, see: https://github.com/input-output-hk/polkadot-sdk/pull/10 .
=> ETCM-8226 - move custom aura consensus, slots and inherents modifications to partner-chains

pallets/native-token-management/src/lib.rs, pallets/native-token-management/src/tests.rs
Fixes the issue where `create_inherent` skips inherent creation when 0 tokens have been transfered, but `is_inherent_required` still expected an inherent to be present
for you.
=> fix: native token inherent check when no tokens transfered

Cargo.lock, Cargo.toml, changelog.md, node/src/staging.rs, node/src/template_chain_spec.rs, node/src/testnet.rs, pallets/pallet-session-runtime-stub/Cargo.toml, pallets/pallet-session-runtime-stub/src/lib.rs, pallets/partner-chains-session/Cargo.toml, pallets/partner-chains-session/src/lib.rs, primitives/session-manager/Cargo.toml, primitives/session-manager/src/lib.rs, runtime/Cargo.toml, runtime/src/lib.rs, runtime/src/mock.rs
Changes:
* depends on polkadot-sdk with removed partner chains session and grandpa modifications
* moved the partner-chains-session
* NOT moved sp-partner-chains-session, because it was only providing CurrentSessionIndex that was only used by modified grandpa, so it was not used anymore
* added pallet-session-runtime-stub and used it in runtime wiring - this is the new code and area where I need your critique the most
~- [ ] New tests are added if needed and existing tests are updated.~ Only moved meaningful code.
~- [ ] Any changes are noted in the `changelog.md` for affected crate ~ - I'll update global changelog when the code is approved
=> feat: move partner chains session pallet from polkadot-sdk fork

mainchain-follower/mock/src/block.rs, node/src/main_chain_follower.rs
Removes the direct environment variable read in `BlockDataSourceMock`. This removes the requirement on the application level for setting an environment variable.
for you.
=> feat: remove env-var read from BlockDataSourceMock

Cargo.lock, Cargo.toml, changelog.md, cli/node-commands/src/lib.rs, mainchain-follower/db-sync-follower/src/data_sources.rs, node/src/command/mod.rs, node/src/main_chain_follower.rs, node/src/service.rs
Using Runner without Partner Chains changes. This required either to:
* creating DataSources outside `new_partial` and injecting them there
* blocking running them and making `new_partial` sync.
I've chosen the latter approach to have command dispatch code similar to templates in polkadot-sdk. Otherwise it would go in the opposite direction - making the diff bigger.
I've tested manually all of our custom command, key generate, chain-info, and running the node.
=> feat: revert usage of custom Runner from polkadot-sdk fork

Cargo.lock, Cargo.toml, changelog.md, node/Cargo.toml, node/src/chain_spec.rs, node/src/command/mod.rs, node/src/staging.rs, node/src/template_chain_spec.rs, node/src/testnet.rs, node/src/tests/runtime_api_mock.rs, pallets/native-token-management/src/lib.rs, primitives/authority-selection-inherents/src/authority_selection_inputs.rs, primitives/authority-selection-inherents/src/runtime_api_mock.rs, primitives/chain-params/Cargo.toml, primitives/chain-params/src/lib.rs, primitives/native-token-management/Cargo.toml, primitives/native-token-management/src/lib.rs, primitives/session-validator-management/Cargo.toml, primitives/session-validator-management/query/src/lib.rs, primitives/session-validator-management/src/lib.rs, primitives/sidechain-slots/Cargo.toml, primitives/sidechain-slots/src/lib.rs
Moves logic that reads from the environment:
- sidechain params
- selection MC scripts
- native token MC scripts
to their respective crates
for you.
=> change: ETCM-8262 move reading of config env vars out of the node crate

Cargo.lock, changelog.md, pallets/session-validator-management/Cargo.toml, pallets/session-validator-management/src/lib.rs
Just an extrinsic to change the MC addresses for registrations/d-param, so we can easily migrate whenever these change due to PCSC upgrade.
for you.
=> change: Add a set_main_chain_scripts extrinsic to validator-management pallet

node/src/staging.rs, node/src/template_chain_spec.rs, node/src/testnet.rs, runtime/src/lib.rs
This change is done with possible migration to usage of properly wired polkadot-sdk `pallet_session`, which is currently wired in with stub implementations only.
Names that are currently used in this implementation do matter and affect storage keys and are present in polkadot-ui.
For this reason I think that `polkadot_session_stub_for_grandpa` name was a mistake.
Name `session` is already used by our pallet, so I've chosen `pallet_session`.  I was wondering about `polkadot_session` as well.
=> feat: rename pallet_session in reference runtime

dev/local-environment/setup.sh, docker/sidechain-dependencies/docker-compose.yml, docs/user-guides/chain-builder.md, docs/user-guides/permissioned.md, docs/user-guides/registered.md, flake.lock, flake.nix, nix/shell.nix
Bump dbsync to 15.3.0.2
Cardano 9.1.1 has a hotfix for post Chang chains (doesn not require a db replay). I thought we should be up to date.
Not sure dbsync is important to upgrade but why not? It works fine (passed all e2e tests on PC Local Env)
to the issue.
for you.
=> Bump cardano node to 9.1.1

dev/local-environment/configurations/pc-contracts-cli/entrypoint.sh
To save time in our e2e tests, we're removing charlie and eve registrations from the local dev environment config.
to the issue.
for you.
=> ETCM-8446 remove charlie from permissioned and eve from registered

Cargo.lock, cli/node-commands/Cargo.toml, client/consensus/aura/Cargo.toml, pallets/native-token-management/Cargo.toml, primitives/chain-params/Cargo.toml, primitives/consensus/aura/Cargo.toml, primitives/native-token-management/Cargo.toml, primitives/session-validator-management/query/Cargo.toml, runtime/Cargo.toml
Some crates were missed when upgrading to 1.1.0 in https://github.com/input-output-hk/partner-chains/commit/41a924a615583979225becefef48e9f084deca32
=> fix: upgrade some previously missed crates to 1.1.0

partner-chains-cli/src/create_chain_spec/tests.rs, partner-chains-cli/src/generate_keys/tests.rs, partner-chains-cli/src/prepare_configuration/mod.rs, partner-chains-cli/src/prepare_configuration/prepare_cardano_params.rs, partner-chains-cli/src/prepare_configuration/prepare_chain_params.rs, partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, partner-chains-cli/src/register/register1.rs, partner-chains-cli/src/register/register2.rs, partner-chains-cli/src/register/register3.rs, partner-chains-cli/src/setup_main_chain_state/tests.rs, partner-chains-cli/src/start_node/tests.rs, partner-chains-cli/src/tests/config.rs, partner-chains-cli/src/tests/mod.rs
Changed the helpers that assert empty IO and results to macro rules, so the test errors show the line within the test case, not the helper definition.
I would love to find a way to show the error at the line of the `MockIO` that caused the error, but it's more tricky here in Rust than would be in Scala with the scope implicit. 
for you.
=> change: better result and IO assertions in CLI tests

partner-chains-cli/src/tests/mod.rs
Quick fix to https://github.com/input-output-hk/partner-chains/pull/91 . `Drop` was triggered when the test
already failed and the thread was unwinding, which killed the whole test runner.
for you.
=> fix: do not panic again in mock IO context's drop

changelog.md, mainchain-follower/main-chain-follower-api/src/mock_services.rs, node/src/tests/inherent_data_tests.rs, node/src/tests/runtime_api_mock.rs, pallets/native-token-management/src/lib.rs, primitives/native-token-management/src/lib.rs, primitives/native-token-management/src/tests/mod.rs, primitives/native-token-management/src/tests/runtime_api_mock.rs, runtime/src/lib.rs
Makes the scripts optional in the native token pallet. If they're absent, the IDP will not query the main chain state at all and will not trigger the inherent.
for you.
=> change: ETCM-8366 Make native token scripts optional

Cargo.lock, changelog.md, primitives/native-token-management/Cargo.toml, primitives/native-token-management/src/lib.rs, primitives/native-token-management/src/tests/mod.rs
This PR:
* adds a `new_for_runtime_version` factory for the native token inherent data provider, which accepts an additional predicate `RuntimeVersion -> bool` to determine whether data should be produced.
* makes the `token_amount` in the IDP an `Option` with `Some` values being non-zero
This PR is part of the work to enable the migration strategy submitted for review in https://github.com/input-output-hk/partner-chains/pull/97 .
for you.
=> change: ETCM-8366 Runtime version-bound native token IDP

changelog.md, node/src/tests/runtime_api_mock.rs, pallets/native-token-management/src/lib.rs, pallets/native-token-management/src/tests.rs, primitives/native-token-management/src/lib.rs, primitives/native-token-management/src/tests/runtime_api_mock.rs, runtime/src/lib.rs
This PR adds a boolean storage `Initialized` to the native token pallet, which is used by the inherent data provider to optionally query for utxos without a lower bound. This is meant to handle the case when some token transfers were made before the pallet was added to an already running chain - since the usual mechanism queries from last to current MC hash, we'd be losing the old transactions; for a new chain this was handled by detecting genesis block as parent.
This PR is part of the work to enable the migration strategy submitted for review in https://github.com/input-output-hk/partner-chains/pull/97 .
You will need to get someone with write privileges.  Please contact IOG Partner Chains …
=> change: ETCM-8366 handle initial loading of historical native token data

partner-chains-cli/src/tests/mod.rs
Better error messages when wrong IO is called in CLI tests, including file name and line number. Example:
```
---- register::register1::tests::happy_path stdout ----
thread 'register::register1::tests::happy_path' panicked at partner-chains-cli/src/tests/mod.rs:241:17:
assertion failed: `(left == right)`: Invalid prompt displayed
Diff < left / right > :
<path to the cardano node socket file
>path to the node socket file
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mock IO defined at partner-chains-cli/src/register/register1.rs:736
```
This would have been much more useful when we were starting, but oh well...
You will need to get someone with write …
=> change: Print file and line number for missed MockIO

Earthfile, changelog.md, docker/builder.Dockerfile, docker/chain-spec/Dockerfile, nix/shell.nix, partner-chains-cli/src/register/register1.rs, rust-toolchain.toml
Polkadot-sdk has moved to 1.81.0. Perhaps we can do it as well.
for you.
=> chore: update rust toolchain after polkadot-sdk

nix/shell.nix
On a fresh OS, my build failed:
```
Compiling openssl v0.10.64
Compiling webpki-roots v0.25.4
error: failed to run custom build command for `openssl-sys v0.9.102`
Caused by:
process didn't exit successfully: `/home/lglo/iohk/partner-chains/target/release/build/openssl-sys-b78964e6dae045b0/build-script-main` (exit status: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
OPENSSL_NO_VENDOR unset
OUT_DIR = Some(/home/lglo/iohk/partner-chains/target/release/build/openssl-sys-a3de202ef55a8efc/out)
cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
CC_x86_64-unknown-linux-gnu = None
cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu …
```
=> fix: 'cargo build' should not fail because of missing perl

mainchain-follower/db-sync-follower/src/native_token/mod.rs, mainchain-follower/mock/src/native_token.rs, node/src/main_chain_follower.rs, primitives/native-token-management/src/lib.rs, primitives/native-token-management/src/tests/mod.rs
Removes the type parameter `Error` of the `NativeTokenDataSource` trait and uses `Box<dyn Error + Send + Sync>` instead. There was no real benefit to keeping it generic.
for you.
=> change: use boxed error for native token IDP error

Cargo.lock, Cargo.toml, changelog.md, utils/ogmios-client/Cargo.toml, utils/ogmios-client/src/jsonrpsee.rs, utils/ogmios-client/src/lib.rs, utils/ogmios-client/src/query_ledger_state.rs, utils/ogmios-client/src/query_network.rs, utils/ogmios-client/src/types.rs, utils/ogmios-client/tests/query_ledger_state.rs, utils/ogmios-client/tests/query_network.rs, utils/ogmios-client/tests/server/mod.rs
* Currently minimal functionality that will allow getting "network parameters" in pc-cli.
* Allows change of the backend, currently it is jsonrpsee, but it has some drawbacks
* Traits for nicer syntax
Anticipated development of this is adding query for UTXOs for given address - to not use cardano-cli for it and submitTx/evaluateTx for offchain-code.
for you.
=> Ogmios client lib - minimal functionality

Cargo.lock, changelog.md, primitives/domain/src/lib.rs, primitives/session-manager/Cargo.toml, primitives/session-manager/src/lib.rs, primitives/session-manager/src/pallet_session_support.rs, utils/plutus/plutus-datum-derive/src/lib.rs
This simple integration allows to run a partner chain without using our custom `pallet-partner-chains-session`, using standard polkadot-sdk `pallet-session`.
It is known that this implementation has additional lag of one partner chains epoch when applying committees to sessions.
When `pallet-session` is used instead of `pallet-partner-chains-session` users have to call `setKeys` in `pallet-session`.
for you.
=> Implement pallet_session_validator_managment and pallet_session integration

changelog.md, docs/developer-guides/native-token-migration-guide.md, primitives/native-token-management/src/lib.rs
Changes the native tokens IDP's `new_for_runtime_version` to `new_if_pallet_present`, which only creates the IDP if the pallet is *currently* in the runtime. This should make adding the native token feature to an existing chain easier.
I tested the upgrade scenario with 3 local nodes.
for you.
=> change: simplify version-bound creation of native token IDP

nix/shell.nix
macOS devShells would build, but cargo itself was not able to build the project because of native dependency mixup with having clang provided by pkgs.clang instead of the apple-sdk specific versions. The project now builds the same with cargo on macOS as it does on linux.
Test by entering the devshell and running `cargo clean` and `cargo build`, to verify the whole project builds.
for you.
=> fix: correct macos shell errors with native deps

mainchain-follower/db-sync-follower/src/candidates/datum/d_param.rs, mainchain-follower/db-sync-follower/src/candidates/datum/mod.rs, mainchain-follower/db-sync-follower/src/candidates/datum/permissioned.rs, mainchain-follower/db-sync-follower/src/candidates/datum/registered.rs, mainchain-follower/db-sync-follower/src/candidates/mod.rs, mainchain-follower/db-sync-follower/src/db_model.rs, primitives/native-token-management/src/lib.rs
This PR is quite big, but 90% of it is moving stuff around:
* Moves parsing of Ariadne datums in db-sync-follower to a separate `datum` module with minimal changes.
* For each datum that we parse, adds a new *Datum enum with a single variant `V0` as a starting point and uses it as an intermediate schema, castable to data expected by the *DataSource traits.
This PR doesn't yet add any logic to parse the new versioned datums, only prepares the structure and defaults to using the legacy parsing methods. I will do this in a separate PR after the implementation in smart contracts is finished and I can get some real datums onto preview.
You will need to get someone with write privileges.  Please …
=> change: ETCM-8716 prepare to support versioned datums

Cargo.lock, Cargo.toml, mainchain-follower/db-sync-follower/Cargo.toml, mainchain-follower/db-sync-follower/src/candidates/datum/d_param.rs, mainchain-follower/db-sync-follower/src/candidates/datum/mod.rs, mainchain-follower/db-sync-follower/src/candidates/datum/permissioned.rs, mainchain-follower/db-sync-follower/src/candidates/datum/registered.rs, mainchain-follower/db-sync-follower/src/candidates/mod.rs, mainchain-follower/db-sync-follower/src/db_datum.rs, mainchain-follower/db-sync-follower/src/db_model.rs, mainchain-follower/db-sync-follower/src/lib.rs, runtime/Cargo.toml
Removes dependency on our `plutus` crate from `db-sync-follower` and replaces it with `cardano-serialization-lib`.
for you.
=> change: ETCM-8721 parse datums with cardano-serialization-lib

partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs
Fix the following warning about unused imports
```
warning: unused import: `Context`
--> partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs:15:22
|
15 | use anyhow::{anyhow, Context};
|                      ^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `partner-chains-cli` (bin "partner-chains-cli") generated 1 warning (run `cargo fix --bin "partner-chains-cli"` to apply 1 suggestion) 
```
for you.
=> Remove unused import

mainchain-follower/db-sync-follower/src/candidates/datum/registered.rs, mainchain-follower/db-sync-follower/src/candidates/mod.rs, mainchain-follower/db-sync-follower/testdata/migrations/6_insert_transactions.sql
This part is required to make the RegisterValidatorDatum available to offchain code.
It is a clear indication that (as we call them) Datums are part of public interface and shouldn't really be buried in db-sync-follower, but I'm not going to fix this in this PR.
Another defect is the `MainchainAddressHash` name, which should be `MainchainKeyHash` instead. It can be observed by looking at the constructor:
```rust
impl MainchainAddressHash {
pub fn from_vkey(vkey: [u8; 32]) -> Self {
Self(blake2b(&vkey))
}
}
```
where we literally hash the key, not the address.
- [ x Self-reviewed the diff
You will need to get someone with write privileges.  Please contact IOG Partner Chains developers to do …
=> feat: make RegisterValidatorDatum usable for offchain code

.github/workflows/cd.yml
fixes:
- wait-for-n2-epoch is running exactly 24h so I'm adding 10 minutes more
for you.
=> fix: wait for n2 epoch

Cargo.lock, Cargo.toml, toolkit/offchain/Cargo.toml, toolkit/offchain/src/csl.rs, toolkit/offchain/src/lib.rs, toolkit/offchain/src/scripts_data.rs, toolkit/offchain/src/untyped_plutus.rs, utils/plutus/src/lib.rs
Code to get what `pc-contracts-cli addresses` return. It is a mix of UPLC and CSL.
It awaits v6.2.2 release of smart-contracts.
Also at v7.0.0 more scripts will use versioning system, so the logic will change towards what native-token uses at the moment.
for you.
=> feat: add pure logic for getting smart-contracts addresses, hashes and policy ids

changelog.md, dev/local-environment/setup.sh, flake.lock, flake.nix
Bump partner-chains-smart-contracts to v6.2.2 (https://github.com/input-output-hk/partner-chains-smart-contracts/releases/tag/v6.2.2)
for you.
=> chore: bump partner-chains-smart-contracts to v6.2.2

toolkit/primitives/plutus-data/src/d_param.rs, toolkit/primitives/plutus-data/src/lib.rs, toolkit/primitives/plutus-data/src/permissioned_candidates.rs, toolkit/primitives/plutus-data/src/registered_candidates.rs
* Adds parsing of versioned datums of schema version 0, equivalent to the legacy schema
* Adds general framework for parsing versioned datums via `VersionedDatum` trait
The tests cases are taken from the golden tests in smart contracts repo. Once the smart contracts changes are merged, I will verify with local chain and real plutus data on preview before merging this PR.
for you.
=> change: ETCM-8722 parse datums V0

E2E-tests/report_slack.sh
Remove xray report links for non-testing slack notifications
for you.
=> fix: remove xray link from slack notifier if xray id is null

changelog.md, toolkit/partner-chains-cli/src/config.rs, toolkit/partner-chains-cli/src/deregister/tests.rs, toolkit/partner-chains-cli/src/ogmios/mod.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_cardano_params.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/register/register1.rs, toolkit/partner-chains-cli/src/register/register3.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/start_node/tests.rs
network id wasn't  network_magic - it was a bug.
`CardanoNetwork`, since we query ogmios for network parameters, doesn't need to know network id, so the type can now be simplified and it's sole purpose is for invoking pc-smart-contracts. When we write offchain in Rust, it will go away completly. 
BTW#2 - this parameter is redundant in pc-smart-contracts, they should be able to figure out network from Ogmios.
for you.
=> fix: CardanoNetwork in pc-cli should not be feed with 'network-magic' but with 'network'

node/runtime/src/lib.rs
Removes `Balances::deposit` from native token transfer handler, which caused problems when the total transfer was less than the existential token amount. This "feature" was only added for visibility and is not needed by anyone.
for you.
=> remove usage of Balances::deposit from transfer handler

E2E-tests/src/blockchain_api.py, E2E-tests/src/substrate_api.py, E2E-tests/tests/committee/test_committee.py
fixes:
- For cases where an SPO had all registrations invalid we no longer return empty list. That fixes the issue with calculating committee participation probability if T > 0 and SPO has no valid registrations.
Refs: ETCM-8662
for you.
=> fix: don't return empty list of registrations

Cargo.lock, toolkit/offchain/src/csl.rs, toolkit/offchain/src/scripts_data.rs, toolkit/partner-chains-cli/src/config.rs, toolkit/partner-chains-cli/src/deregister/mod.rs, toolkit/partner-chains-cli/src/ogmios/mod.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_cardano_params.rs, toolkit/partner-chains-cli/src/register/register1.rs, toolkit/partner-chains-cli/src/register/register3.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/mod.rs, toolkit/primitives/domain/src/lib.rs, toolkit/utils/ogmios-client/Cargo.toml, toolkit/utils/ogmios-client/src/query_network.rs, toolkit/utils/ogmios-client/tests/query_network.rs
Introduces a `NetworkType` enum in the domain crate and replaces local types representing Cardano network type from other crates.
for you.
=> change: Migrate to a common Cardano network type in domain crate

toolkit/offchain/src/init_governance/tests.rs, toolkit/offchain/src/ogmios_mock.rs
UTXOs have address in them, so passing it additionally makes some risk of inconsistent data in mock and requires redundant specification of the address
to the issue.
~- [ ] New tests are added if needed and existing tests are updated.~
~- [ ] Any changes are noted in the `changelog.md` for affected crate~
=> feat: don't require utxos address to be passed to ogmios mock

changelog.md, pallets/sidechain/src/lib.rs, runtime/src/lib.rs
Adds an `upgrade_and_set_addresses` extrinsic to Sidechain pallet which allows to atomically upgrade the runtime and change chain configuration at the same time.
for you.
=> change: Extrinsic enabling update from v1.3 to v1.4

dev/nix/packages/default.nix, dev/nix/packages/pc-contracts-cli.nix, dev/nix/shell.nix, flake.lock, flake.nix
`partner-chains-smart-contracts` repo will stop providing nix derivations. This PR makes nix get `pc-contracts-cli` from the release archive instead.
for you.
=> chore: avoid using nix derivations defined in pc-contracts repo

E2E-tests/config/api_config.py, E2E-tests/config/substrate/local_nodes.json, E2E-tests/config/substrate/staging_nodes.json, E2E-tests/src/blockchain_api.py, E2E-tests/src/sidechain_main_cli.py, E2E-tests/src/substrate_api.py, E2E-tests/tests/committee/test_committee.py
=> ETCM-8250 test update d param

docs/user-guides/chain-builder.md, toolkit/cli/smart-contracts-commands/src/init_governance.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/init_governance/tests.rs, toolkit/partner-chains-cli/src/io.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/tests/mod.rs
Adds run_init_governance step in `prepare-configuration` wizard step.
[link](https://input-output.atlassian.net/browse/ETCM-8880)
for you.
=> Etcm 8880 gov init in wizard

changelog.md, toolkit/cli/smart-contracts-commands/src/get_scripts.rs, toolkit/cli/smart-contracts-commands/src/init_governance.rs, toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/offchain/src/scripts_data.rs
Adds `get-scripts` command that prints all validator addresses and policy IDs for a given genesis utxo.
for you.
=> add: ETCM-8948 get-scripts command

Cargo.lock, Cargo.toml, toolkit/cli/smart-contracts-commands/Cargo.toml, toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/cli/smart-contracts-commands/src/main.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/partner-chains-cli/Cargo.toml, toolkit/partner-chains-cli/src/main.rs, toolkit/utils/ogmios-client/Cargo.toml, toolkit/utils/ogmios-client/src/jsonrpsee.rs, toolkit/utils/ogmios-client/src/lib.rs
Logs Ogmios requests and responses into `ogmios_client.log` file in HttpClient. There's some hoops to jump through to log json values because we're using jsonrpsee which hides them. I thought about introducing a wrapper type for HttpClient which would make it possible to configure the file to which we log but I'm not convinced it's really needed. 
I went with the simples 
for you.
=> change: ETCM-8907 add logging of ogmios requests

pallets/sidechain/src/lib.rs
Normal dispatch class is affected by block weight limits. `upgrade_and_set_addresses` by necessity consumes all remaining weight of the block (this behaviour comes form `set_code`), which on my local chain caused it to never be included in a block. Changing the dispatch class to operational removes this issue. 
for you.
=> fix: Change upgrade_and_set_addresses dispatch class to Operational

changelog.md, toolkit/offchain/src/d_param/mod.rs, toolkit/partner-chains-cli/src/cardano_key.rs, toolkit/partner-chains-cli/src/io.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/mod.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/tests/mod.rs, toolkit/primitives/domain/src/lib.rs
Uses the native Rust offchain implementation to update D-Param in the `setup-main-chain-state` command in wizard.
for you.
=> change: ETCM-8949 use native upsert_d_param in wizard

.gitignore, Cargo.lock, toolkit/cli/smart-contracts-commands/Cargo.toml, toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/cli/smart-contracts-commands/src/register.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/lib.rs, toolkit/offchain/src/register.rs, toolkit/offchain/src/scripts_data.rs, toolkit/primitives/domain/src/lib.rs, toolkit/primitives/plutus-data/src/registered_candidates.rs
This PR implements candidate registration transaction submission and provides a CLI for it as well.
for you.
=> ETCM-8754: implement register tx submit

.github/workflows/devnet.yml, .github/workflows/staging.yml, E2E-tests/pytest.ini
test: fix e2e tests debug log format
Refs: ETCM-7672
for you.
=> test: fix e2e tests debug log format

docs/developer-guides/migration-guide-1.4.0.md
=> chore: Migration guide corrections

toolkit/offchain/src/register.rs, toolkit/offchain/tests/integration_tests.rs, toolkit/primitives/domain/src/lib.rs
Register had two issues:
* it always tried to calculate exunits, even when there was no need (thanks Lech)
* it was comparing the entire registration datum when checking for existing registrations, even though the registration utxo can differ for registering the same keys
This PR fixes these issues and enables the integration test for the register command.
for you.
=> ETCM-8754: fix register command

Cargo.lock, toolkit/cli/smart-contracts-commands/Cargo.toml, toolkit/cli/smart-contracts-commands/src/lib.rs
Our registration-signatures command outputs:
```
{"spo_public_key":"0x08accadc8b60a5f519ee74ab144ada6993709f5479152f9217688889d8a2db2e","spo_signature":"0x040a8b9f336986fe5cea10a3bfcd6fb4f84dceda8e00ca23eee6e28af0605fb86fd96b41746df159b318b5075e067ce30e67d2bf5fef3e21f01a48325e375a06","sidechain_public_key":"0x039799ff93d184146deacaa455dade51b13ed16f23cdad11d1ad6af20103391180","sidechain_signature":"0xf0905c8d5a4db6075f76f6628282b3e257ffa1184ba2e35cd34415968d360d7452c981d171b4f22489690994a46026c1c1801df3e83f1038d4f20bb8affdfbcd"}
```
, so it is not nice to not accept 0x prefix at input.
With this modification such command is accepted:
```
target/debug/partner-chains-node smart-contracts register --genesis-utxo c389187c6cabf1cd2ca64cf8c76bf57288eb9c02ced6781935b810a1d0e7fbb4#0 …
```
=> fix: parse keys with 0x prefix

toolkit/offchain/src/plutus_script.rs, toolkit/offchain/src/scripts_data.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs
Use PascalCase for policy ids and remove validator hashes
for you.
=> chore: use PascalCase for PolicyIds and remove ValidatorHashes because its unused

Cargo.lock, toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/cli/smart-contracts-commands/src/register.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/register.rs, toolkit/offchain/tests/integration_tests.rs, toolkit/partner-chains-cli/src/cardano_key.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/primitives/domain/Cargo.toml, toolkit/primitives/domain/src/lib.rs
=> ETCM-8753: implement deregister command

toolkit/primitives/domain/src/lib.rs, toolkit/primitives/native-token-management/src/lib.rs, toolkit/primitives/native-token-management/src/tests/mod.rs
Error message were always displaying 0 tokens before changes here.
for you.
=> bugfix: implement Display for NativeTokenManagement and fix error formatting

changelog.md, toolkit/mainchain-follower/db-sync-follower/src/native_token/mod.rs, toolkit/mainchain-follower/db-sync-follower/src/native_token/tests.rs, toolkit/mainchain-follower/db-sync-follower/testdata/native-token/migrations/2_data.sql, toolkit/mainchain-follower/mock/src/native_token.rs, toolkit/primitives/native-token-management/src/lib.rs
Before the cache for native tokens queries was returning cached results for the wrong main chain scripts
Turn off whitespaces in diff when reviewing this PR
for you.
=> fix: invalidate cache when main chain scripts are different than in the previous query

toolkit/offchain/src/csl.rs, toolkit/offchain/src/d_param/mod.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/lib.rs, toolkit/offchain/src/plutus_script.rs, toolkit/offchain/src/reserve/init.rs, toolkit/offchain/src/reserve/mod.rs, toolkit/offchain/tests/integration_tests.rs
Requires follow ups:
* unit tests for transaction properties, ones written in the header of init.rs file
* implementation of idempotency
* implement command
for you.
=> feat: add init-reserve-management smart contract execution

.github/workflows/ci.yml, toolkit/offchain/src/d_param/mod.rs, toolkit/offchain/src/d_param/tests.rs, toolkit/offchain/src/plutus_script.rs, toolkit/offchain/tests/integration_tests.rs
Fixes the bug with ExUnits.
[link](https://input-output.atlassian.net/browse/ETCM-9054)
for you.
=> Fix upsert-d-param ExUnit error

toolkit/offchain/src/reserve/init.rs, toolkit/offchain/tests/integration_tests.rs
Do not try to build and submit any script initialization if there is a proof on the chain, that it has already been initialized.
for you.
=> feat: implement idempotency for init-reserve-management

changelog.md, toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/cli/smart-contracts-commands/src/reserve.rs
* Added subcommand `reserve` and its command `init`.
```
./partner-chains-node smart-contracts reserve init --help
Initialize the reserve management system for your chain
Usage: partner-chains-node smart-contracts reserve init [OPTIONS] --payment-key-file <PAYMENT_KEY_FILE> --genesis-utxo <GENESIS_UTXO>
```
Logs from invocation:
```
./partner-chains-node smart-contracts reserve init -k payment.skey -c c389187c6cabf1cd2ca64cf8c76bf57288eb9c02ced6781935b810a1d0e7fbb4#1
2024-12-31T08:03:13.116031291+01:00 INFO partner_chains_cardano_offchain::reserve::init - Initialized Versioned 'Reserve Management Validator' transaction submitted: cec190d8187ade25c749819b8b330cbad79866d0cdb2759c7ca3eb009e4852bd
2024-12-31T08:03:13.116057881+01:00 INFO partner_chains_cardano_offchain::await_tx - Probing for …
```
=> feat: implement 'reserve init' command

toolkit/partner-chains-cli/src/prepare_configuration/init_governance.rs, toolkit/partner-chains-cli/src/prepare_configuration/mod.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_chain_params.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/prepare_configuration/select_genesis_utxo.rs, toolkit/primitives/domain/src/lib.rs
Moves init-goveranance just after asking for the genesis utxo and removing now unnecessary caution.
Please run the old and the new code to see if you also find the behavior better.
for you.
=> feat: Move run init-goveranance just after choosing the genesis-utxo

E2E-tests/config/substrate/local_nodes.json, dev/local-environment/configurations/cardano/entrypoint.sh, dev/local-environment/configurations/cardano/reward_token_policy.script, dev/local-environment/modules/cardano.txt
In local-environment we make the first transaction to fund addresses. This PR modifies this transaction, so it also mints a Cardano Native Token with a policy allowing funded_address.skey to mint it and name "Reward token". It is meant for testing "rewards management".
=> feat: add a native token to the initial transaction in the local-environment

changelog.md, toolkit/cli/smart-contracts-commands/src/reserve.rs, toolkit/offchain/src/reserve/create.rs, toolkit/primitives/domain/src/lib.rs
Adds `reserve create` command to CLI.
Example:
```
./partner-chains-node smart-contracts reserve create \
-c 61ca664e056ce49a9d4fd2fb3aa2b750ea753fe4ad5c9e6167482fd88394cf7d#0 \
--token 1fab25f376bc49a181d03a869ee8eaa3157a3a3d242a619ca7995b2b.52657761726420746f6b656e \
--t0 1735689600 \
--total-accrued-function-script-hash c389187c6cabf1cd2ca64cf8c76bf57288eb9c02ced6781935b810a1 \
--initial-deposit-amount 500000 \
--initial-incentive-amount 1000 \
-k funded_address.skey
2025-01-07T16:52:26.624180624+01:00 INFO partner_chains_cardano_offchain::reserve::create - Create Reserve transaction submitted: 04d2bdd2b9caeca2f80c4b7a459f518f14dc13ed01c265d47ab5c9f725368806
2025-01-07T16:52:26.624199549+01:00 INFO partner_chains_cardano_offchain::await_tx - Probing for transaction output …
```
=> Reserve create CLI command

.github/actions/images/build-and-publish-ecr/action.yml, .github/workflows/cd.yml
Successful build and deploy:
https://github.com/input-output-hk/partner-chains/actions/runs/12668053264
=> feat: Pin CD.yml binary build to ubuntu 22.04, and match ECR image to the same version

toolkit/cli/smart-contracts-commands/src/d_parameter.rs, toolkit/cli/smart-contracts-commands/src/governance.rs, toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/cli/smart-contracts-commands/src/register.rs, toolkit/cli/smart-contracts-commands/src/reserve.rs
1.
```
./partner-chains-node smart-contracts init-governance -c 61ca664e056ce49a9d4fd2fb3aa2b750ea753fe4ad5c9e6167482fd88394cf7d#0 -k payment.vkey -g e8c300330fe315531ca89d4a2e7d0c80211bc70b473b1ed4979dff2b
Error: Application("Could not read private key file. Reason: Unsupported key type: PaymentVerificationKeyShelley_ed25519. Expected a signing key")
```
Instead of failing transaction because of missing funds when verification key is used in place of signing key.
2. Added help messages to params in `register` and `deregister`:
```
./target/debug/partner-chains-node smart-contracts register --help
Register candidate
Usage: partner-chains-node smart-contracts register [OPTIONS] --genesis-utxo <GENESIS_UTXO> --registration-utxo <REGISTRATION_UTXO> --payment-key-file <PAYMENT_KEY_FILE> …
```
=> feat: improve handling of payment key argument and add documentation for some other fields

toolkit/cli/smart-contracts-commands/src/d_parameter.rs, toolkit/offchain/src/d_param/mod.rs, toolkit/offchain/src/permissioned_candidates.rs, toolkit/offchain/tests/integration_tests.rs
Not awaiting for the output being present made it possible that the following transactions fail, because they query wallet before previous transaction being observable but try to submit it after. Happened during testing wizards.
=> fix: await upsert-d-parameter and upsert-permissioned-candidates transaction outputs being present

E2E-tests/config/substrate/staging_nodes.json, E2E-tests/config/substrate/staging_stack.json, E2E-tests/src/blockchain_api.py, E2E-tests/src/substrate_api.py, E2E-tests/tests/committee/test_blocks.py, E2E-tests/utils/pc_epoch_calc.py
=> Etcm 8983 fix get block author test

toolkit/primitives/plutus-data/src/d_param.rs, toolkit/primitives/plutus-data/src/lib.rs, toolkit/primitives/plutus-data/src/permissioned_candidates.rs, toolkit/primitives/plutus-data/src/registered_candidates.rs, toolkit/primitives/plutus-data/src/reserve.rs
Simplifies `VersionedDatum` trait to only include `fn decode` and adds a `VersionedDatumWithLegacy` that covers the original legacy/versioned decoding.
for you.
=> introduce VersionedDatumWithLegacy trait

toolkit/offchain/src/csl.rs, toolkit/offchain/src/d_param/tests.rs, toolkit/offchain/src/init_governance/transaction.rs, toolkit/offchain/src/permissioned_candidates.rs, toolkit/offchain/src/plutus_script.rs, toolkit/offchain/src/reserve/create.rs, toolkit/offchain/src/reserve/init.rs, toolkit/offchain/src/reserve/mod.rs, toolkit/offchain/src/scripts_data.rs, toolkit/offchain/src/test_values.rs, toolkit/offchain/src/update_governance/mod.rs, toolkit/offchain/src/update_governance/test.rs, toolkit/primitives/plutus-data/src/reserve.rs
* adds reserve redeemer type + plutus data conversion
* changes uses of LanguageKind to Language (can't easily get Language from LanguageKind, but can get do the other way with `.kind()`, and CSL API seems to expect Language usually)
* reserve::find_script_utxo returns OgmiosUtxo because I need it
* turned convert_value into an extension trait to make it easier to find and more consistent with other conversions
for you.
=> ETCM-9064 reserve redeemer and misc changes

toolkit/cli/smart-contracts-commands/src/reserve.rs, toolkit/offchain/src/reserve/create.rs, toolkit/offchain/tests/integration_tests.rs, toolkit/primitives/plutus-data/src/reserve.rs
Removes 't0' from `reserve create` command, as it turned out to be not used by Reserve Validator.
It was misleading at least. If users release functions need "t0", then users are supposed to store it on their own.
for you.
=> fix: hide 't0' parameter of 'reserve create' command

toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/cli/smart-contracts-commands/src/permissioned_candidates.rs, toolkit/offchain/src/permissioned_candidates.rs
[link](https://input-output.atlassian.net/browse/ETCM-9053)
to the issue.
for you.
=> add upsert-permissioned-candidates smart-contracts node command

toolkit/offchain/src/csl.rs, toolkit/offchain/src/d_param/mod.rs, toolkit/offchain/src/permissioned_candidates.rs, toolkit/offchain/src/register.rs, toolkit/offchain/src/reserve/create.rs, toolkit/offchain/src/reserve/deposit.rs, toolkit/offchain/src/reserve/init.rs, toolkit/offchain/src/update_governance/mod.rs
* Merged `add_script_utxo_input` and `add_script_utxo_input_with_data` into one, because  the former assumed too much about redeemer data and is was re-usable only by chance
* `add_mint_one_script_token` - now requires redeemer data to make it really re-usable
* removed redundant `add_required_signer`, because our `balance_update_and_build` does it internally
* removed some redundant `add_script_reference_input`
=> feat: cleanup too specific helpers and make sense of redeemer data 

changelog.md, toolkit/cli/smart-contracts-commands/src/reserve.rs, toolkit/offchain/src/ogmios_mock.rs, toolkit/offchain/src/reserve/deposit.rs, toolkit/offchain/src/reserve/mod.rs, toolkit/offchain/src/reserve/release.rs, toolkit/offchain/tests/integration_tests.rs, toolkit/primitives/plutus-data/src/reserve.rs, toolkit/utils/ogmios-client/src/query_ledger_state.rs
This PR uses helpers split out into https://github.com/input-output-hk/partner-chains/pull/405 .
Implements the reserve releasing transaction, offchain and command.
Also adds a transaction, offchain and command to create a reference utxo with the example v-function from `raw_scripts`. I'm not sure it should be exposed to the users. Let me know what you think.
for you.
=> add: ETCM-9061 reserve release command

toolkit/offchain/src/reserve/deposit.rs, toolkit/offchain/src/reserve/handover.rs, toolkit/offchain/src/reserve/mod.rs, toolkit/offchain/src/reserve/release.rs, toolkit/offchain/src/reserve/update_settings.rs
* Four transactions that spend a Reserve Auth Token now use the same function from crate mod.rs
* DRY in deposit, regarding getting current data
for you.
=> chore: cleanup input with script reference for spending Reserve Auth Token, DRY

toolkit/offchain/src/csl.rs, toolkit/offchain/src/reserve/create.rs, toolkit/offchain/src/reserve/deposit.rs, toolkit/offchain/src/reserve/handover.rs, toolkit/offchain/src/reserve/init.rs, toolkit/offchain/src/reserve/release.rs, toolkit/offchain/src/reserve/update_settings.rs, toolkit/primitives/plutus-data/src/reserve.rs
* Use Cost::calculate_costs in reserve module
* Remove unused parameters from ReserveRedeemer. These arguments were removed from the Plutus smart contracts a while ago, but the change was not reflected in the purescript code which was reimplemented in rust. The way PlutusData encoding works, superfluous fields can be ignored while decoding, so this didn't cause an issue and went unnoticed.
for you.
=> ETCM-9222 generic ExUnit calculation in reserve modules

toolkit/offchain/src/reserve/create.rs, toolkit/offchain/src/reserve/release.rs, toolkit/primitives/plutus-data/src/reserve.rs
This PR makes ReserveDatum in offchain rust code match its counterpart in onchain smart-contract code.
T0 field was ignored during decoding, and hidden from the offchain type, which led to a confusing error when a transaction only intending to change other fields also changed T0 because encoding implicitly sets it to 0.
I would consider it a bad practice in general not to have 1:1 matching encoded/decoded types in onchain and offchain code.
for you.
=> ETCM-9064 make ReserveDatum offchain match onchain

toolkit/cli/node-commands/src/lib.rs, toolkit/cli/smart-contracts-commands/src/governance.rs, toolkit/mainchain-follower/db-sync-follower/src/candidates/mod.rs, toolkit/offchain/src/csl.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/init_governance/tests.rs, toolkit/offchain/src/init_governance/transaction.rs, toolkit/offchain/src/register.rs, toolkit/offchain/src/scripts_data.rs, toolkit/offchain/src/update_governance/mod.rs, toolkit/offchain/src/update_governance/test.rs, toolkit/offchain/tests/integration_tests.rs, toolkit/partner-chains-cli/src/prepare_configuration/init_governance.rs, toolkit/partner-chains-cli/src/register/register3.rs, toolkit/partner-chains-cli/src/tests/mod.rs, toolkit/primitives/domain/src/lib.rs, toolkit/primitives/plutus-data/src/registered_candidates.rs
`MainchainAddressHash` name is just invalid. It is not a hash of address.
=> chore: rename MainchainAddressHash to MainchainKeyHash

toolkit/partner-chains-cli/src/create_chain_spec/tests.rs, toolkit/partner-chains-cli/src/deregister/tests.rs, toolkit/partner-chains-cli/src/generate_keys/tests.rs, toolkit/partner-chains-cli/src/prepare_configuration/init_governance.rs, toolkit/partner-chains-cli/src/prepare_configuration/mod.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/prepare_configuration/select_genesis_utxo.rs, toolkit/partner-chains-cli/src/register/register1.rs, toolkit/partner-chains-cli/src/register/register2.rs, toolkit/partner-chains-cli/src/register/register3.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/start_node/tests.rs, toolkit/partner-chains-cli/src/tests/config.rs, toolkit/partner-chains-cli/src/tests/mod.rs
Step 1 of files operations overspecification clean-up. It is simple, because this is about reads only. We should not care about when something is read or how many times. Mock files are setup in tests and updated by write operations. Nothing else matters.
for you.
=> test-refactor: do not overspecify read operations order or number

toolkit/partner-chains-cli/src/create_chain_spec/tests.rs, toolkit/partner-chains-cli/src/deregister/tests.rs, toolkit/partner-chains-cli/src/generate_keys/tests.rs, toolkit/partner-chains-cli/src/ogmios/config.rs, toolkit/partner-chains-cli/src/prepare_configuration/init_governance.rs, toolkit/partner-chains-cli/src/prepare_configuration/mod.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/prepare_configuration/select_genesis_utxo.rs, toolkit/partner-chains-cli/src/register/register1.rs, toolkit/partner-chains-cli/src/register/register3.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/start_node/tests.rs, toolkit/partner-chains-cli/src/tests/config.rs, toolkit/partner-chains-cli/src/tests/mod.rs
Replaces verification for each JSON field write operation with assertions on the final shape of given file.
`pretty_assertions` are used to diff serde_json::Value, in so error message pretty.
=> test-refactor: do not over-specify file write interactions

changelog.md, docs/user-guides/chain-builder.md, docs/user-guides/permissioned.md, docs/user-guides/registered.md, toolkit/partner-chains-cli/src/config.rs, toolkit/partner-chains-cli/src/create_chain_spec/tests.rs, toolkit/partner-chains-cli/src/deregister/tests.rs, toolkit/partner-chains-cli/src/generate_keys/tests.rs, toolkit/partner-chains-cli/src/lib.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/register/register1.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/start_node/tests.rs
Changes the names of the config files used by wizard commands to be shorter.
for you.
=> change: ETCM-9277 rename wizard config files

toolkit/cli/smart-contracts-commands/src/permissioned_candidates.rs
Before:
```
STDERR: thread 'main' panicked at toolkit/cli/smart-contracts-commands/src/permissioned_candidates.rs:30:14:
Permissioned candidates file with each line representing one candidate: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After:
```
Error: Application("Could not read permissioned candidates file 'oneentry.cv'. Cause: No such file or directory (os error 2)")
```
=> fix: return error instead of panic when permission candidates file is missing

dev/local-environment/configurations/wizard/governance-authority/entrypoint.sh, dev/local-environment/configurations/wizard/permissioned/entrypoint.sh, dev/local-environment/configurations/wizard/registered/entrypoint.sh, dev/local-environment/modules/partner-chains-wizard.txt, dev/local-environment/setup.sh
feat: local-env with wizard-spawned network
Refs: ETCM-9298
for you.
=> feat: local-env with wizard-spawned network

changelog.md, toolkit/pallets/session-validator-management/Cargo.toml, toolkit/pallets/session-validator-management/benchmarking/src/lib.rs, toolkit/pallets/session-validator-management/src/lib.rs, toolkit/pallets/session-validator-management/src/mock.rs, toolkit/pallets/session-validator-management/src/tests.rs, toolkit/primitives/domain/src/byte_string.rs, toolkit/primitives/session-validator-management/src/lib.rs, toolkit/utils/byte-string-derivation/src/lib.rs
* Includes a Blake2 hash of the inherent data used in the `pallet-session-validator-management`'s `set` inherent.
* Includes hash information in the error if the committee doesn't match expected
* Logs a warning if correct committee is selected but a hash mismatch is detected
for you.
=> add: ETCM-8739 include input data hash in committee selection inherent

e2e-tests/src/blockchain_api.py, e2e-tests/src/partner_chains_node.py, e2e-tests/src/substrate_api.py, e2e-tests/tests/committee/conftest.py, e2e-tests/tests/committee/test_permissioned_registrations.py
fixes:
- fixture `permissioned_candidates` now gets the latest active candidates from RPC instead of db to avoid setting the same candidates error
- test_transaction now waits for finalization
- fixture `permissioned_rotation_candidates` now gets the latest status of candidates based on id column
=> test: fix upsert permissioned candidates e2e tests

.github/workflows/cd.yml
fixes:
- check block finalization progress in CD job
- ignore errors until timeout in partner-chain-ready step of CD job
=> CD check block finalization progress

changelog.md, toolkit/offchain/src/csl.rs, toolkit/offchain/src/reserve/mod.rs, toolkit/offchain/src/reserve/release.rs, toolkit/offchain/tests/integration_tests.rs, toolkit/utils/ogmios-client/src/types.rs, toolkit/utils/ogmios-client/tests/query_ledger_state.rs
Fixes the overflow error when user passes `--amount` lower than total of already release amount.
Before:
```
thread 'main' panicked at toolkit/offchain/src/reserve/release.rs:109:30:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After:
```
Error: Application(The requested total amount: 2 is not greater than the amount already transferred to illiquid supply: 10!)
```
=> bugfix: fix reserve release panicking with overflow error

changelog.md, dev/envs/devnet/.envrc, docs/user-guides/chain-builder.md, node/node/src/tests/mock.rs, toolkit/mainchain-follower/db-sync-follower/src/block/mod.rs, toolkit/mainchain-follower/db-sync-follower/src/block/tests.rs, toolkit/pallets/sidechain/rpc/src/tests/mod.rs, toolkit/partner-chains-cli/src/config.rs, toolkit/partner-chains-cli/src/deregister/tests.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_cardano_params.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/register/register3.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/start_node/mod.rs, toolkit/partner-chains-cli/src/start_node/tests.rs, toolkit/primitives/authority-selection-inherents/src/ariadne_inherent_data_provider.rs, toolkit/primitives/domain/src/mainchain_epoch.rs
Cardano slot length was hard-coded to 1000ms. This PR makes it configurable via environment variable, while defaulting back to the original value.
for you.
=> change: ETCM-8437 make cardano slot length configurable

toolkit/cli/smart-contracts-commands/src/d_parameter.rs, toolkit/cli/smart-contracts-commands/src/get_scripts.rs, toolkit/cli/smart-contracts-commands/src/governance.rs, toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/cli/smart-contracts-commands/src/permissioned_candidates.rs, toolkit/cli/smart-contracts-commands/src/register.rs, toolkit/cli/smart-contracts-commands/src/reserve.rs, toolkit/partner-chains-cli/src/ogmios/mod.rs, toolkit/utils/ogmios-client/src/jsonrpsee.rs, toolkit/utils/ogmios-client/tests/query_ledger_state.rs, toolkit/utils/ogmios-client/tests/query_network.rs, toolkit/utils/ogmios-client/tests/transactions.rs
Adds more descriptive error for when connecting to Ogmios client fails.
previously:
```
Error: Application("Couldn't create WebSockets client: Error when opening the TCP socket: Connection refused (os error 61)")
```
with the change:
```
Error: Application("Failed to connect to Ogmios at ws://localhost:1337 with: Couldn't create WebSockets client: Error when opening the TCP socket: Connection refused (os error 111)")
```
for you.
=> ETCM-9199: better error when connecting to ogmios fails

changelog.md, docs/developer-guides/native-token-reserve-management.md, toolkit/cli/smart-contracts-commands/src/reserve.rs, toolkit/offchain/src/reserve/release.rs, toolkit/offchain/tests/integration_tests.rs
Changes `--amount` to the amount that should be released from reserve during this execution of command, not the total amount from the creation of the reserve.
Additionally, `--token` parameter is removed as it was not used by the present code. I don't know if it should or rather it should be removed from `deposit` for example. For sure users would be surprised if they given some asset id but something else was released.
=> feat: make 'reserve release' --amount parameter the amount to release by this execution command

toolkit/mainchain-follower/db-sync-follower/src/db_model.rs, toolkit/mainchain-follower/db-sync-follower/src/stake_distribution/mod.rs, toolkit/mainchain-follower/db-sync-follower/src/stake_distribution/tests.rs, toolkit/primitives/stake-distribution/src/lib.rs
This PR adds 2 more queries for stake distributions:
`get_stake_pool_delegation_distribution_for_pool(McEpochNumber, MainchainKeyHash) -> PoolDelegation`
`get_stake_pool_delegation_distribution_for_pools(McEpochNumber, Vec<MainchainKeyHash>) -> StakeDistribution`
These queries also implement caching through an LRU cache, the key being `(McEpochNumber, MainchainKeyHash)`.
I plan on adding caching to `get_stake_pool_delegation_distribution` in a follow up PR.
for you.
=> ETCM-9305 per pool stake distribution queries with caching

dev/local-environment/setup.sh
chore: set default local-env image to v1.5.0
=> chore: set default local-env image to v1.5.0

Cargo.lock, node/node/Cargo.toml, node/node/src/main_chain_follower.rs, toolkit/mainchain-follower/db-sync-follower/src/stake_distribution/mod.rs, toolkit/mainchain-follower/db-sync-follower/src/stake_distribution/tests.rs, toolkit/mainchain-follower/mock/Cargo.toml, toolkit/mainchain-follower/mock/src/lib.rs, toolkit/mainchain-follower/mock/src/stake_distribution.rs, toolkit/primitives/domain/src/lib.rs, toolkit/primitives/domain/src/mainchain_epoch.rs, toolkit/primitives/native-token-management/src/lib.rs, toolkit/primitives/session-manager/src/pallet_session_support.rs, toolkit/primitives/session-validator-management/src/lib.rs, toolkit/primitives/stake-distribution/src/lib.rs
- changes data source method arguments from vectors to slices
- adds a mock data source
- wires the data source in the node (unused for now, will be used when the payouts pallet is implemented)
- fixes a couple of random compilation warnings caused by not using feature flags etc.
for you.
=> change: Stake data source improvements

e2e-tests/secrets/substrate/staging/staging-ci.json, e2e-tests/secrets/substrate/staging/staging.json, e2e-tests/src/blockchain_api.py, e2e-tests/src/pc_block_finder.py, e2e-tests/src/substrate_api.py, e2e-tests/tests/committee/conftest.py, e2e-tests/tests/committee/test_blocks.py
fixes:
- use cache instead of querying for the same block twice
- get validators once per pc epoch instead on every block
Refs: ETCM-9389
=> test: speed up block rewards tests

e2e-tests/README.md, e2e-tests/docs/run-tests-on-local-env.md, e2e-tests/tests/committee/test_blocks.py
* Adds OFFSET to test_block_headers_have_mc_hash based on specs, allowing for small discrepancy, but logging a warning
* Some improvements to docs
for you.
=> ETCM-8543 Fix test_block_headers_have_mc_hash

node/runtime/src/lib.rs, node/runtime/src/mock.rs, toolkit/primitives/authority-selection-inherents/src/filter_invalid_candidates.rs, toolkit/primitives/authority-selection-inherents/src/select_authorities.rs, toolkit/primitives/authority-selection-inherents/src/tests.rs
Introduces separate types for permissioned/trustless candidates so in the future we could preserve that information in committee data on-chain. I *think* this shouldn't break existing chains but I will need to check that.
UPDATE: Tested this successfully with runtime upgrade on devnet.
for you.
=> change: differentiate two types of candidates in selection process

flake.lock
```
nix flake lock --update-input nixpkgs
```
This PR updates the nixpkgs input to the latest revision. One relevant update is awscli which caused conflicts with other python packages from the e2e-tests project
for you.
=> Update nixpkgs flake input

e2e-tests/README.md, e2e-tests/docs/run-tests-on-local-env.md
* Explains that devshell python is not the way to go
* fixes commands used
* uses specific password required to run tests with local env.
=> docs: minor updates in e2e-tests readme

dev/nix/shell.nix
* nodejs - I'm not aware we need it (something for docs?)
* perl - I recall it was used in some CI, but I can't find it anymore
* kubernetes-helm - we don't have any helm files in this repo, to deploy our private infra we have a private repo, where there are helm files. I keep kubectl, becuase even in docs we use it to open ports to Ogmios or Db-sync from private devnet
=> chore: remove unused packages from devshell

Cargo.lock, changelog.md, dev/local-environment/configurations/partner-chains-setup/entrypoint.sh, node/node/src/staging.rs, node/node/src/testnet.rs, node/runtime/Cargo.toml, node/runtime/src/lib.rs, node/runtime/src/mock.rs, toolkit/pallets/session-validator-management/README.md, toolkit/pallets/session-validator-management/benchmarking/src/lib.rs, toolkit/pallets/session-validator-management/benchmarking/src/mock.rs, toolkit/pallets/session-validator-management/src/lib.rs, toolkit/pallets/session-validator-management/src/migrations/README.md, toolkit/pallets/session-validator-management/src/migrations/mod.rs, toolkit/pallets/session-validator-management/src/migrations/v0.rs, toolkit/pallets/session-validator-management/src/migrations/v1.rs, toolkit/pallets/session-validator-management/src/mock.rs, toolkit/partner-chains-cli/src/create_chain_spec/mod.rs, toolkit/partner-chains-cli/src/create_chain_spec/tests.rs, toolkit/primitives/authority-selection-inherents/Cargo.toml, toolkit/primitives/authority-selection-inherents/src/authority_selection_inputs.rs, toolkit/primitives/authority-selection-inherents/src/filter_invalid_candidates.rs, toolkit/primitives/authority-selection-inherents/src/lib.rs, toolkit/primitives/session-manager/src/lib.rs, toolkit/primitives/session-manager/src/pallet_session_support.rs, toolkit/primitives/session-validator-management/src/lib.rs
IMPORTANT: This is a breaking change and must not be merged without a storage migration ready.
This PR's goal is to make previously missing committee member data available in the runtime: MC pubkey and type of candidate (permissioned, trustless)
* Makes committee member data a generic type in `pallet-session-validator-management::Config`
* Provides a `CommitteeMemberInfo` enum in the runtime to instantiate this generic type, which distinguishes between trustless and permissioned members and contains MC Public Key for the former
Follow up changes necessary:
for you.
=> change: Include candidate type and MC pubkey in committee data in the storage

node/node/src/inherent_data.rs, node/node/src/rpc.rs, node/node/src/tests/runtime_api_mock.rs, node/runtime/src/lib.rs, toolkit/cli/node-commands/src/lib.rs, toolkit/pallets/session-validator-management/src/lib.rs, toolkit/primitives/authority-selection-inherents/src/ariadne_inherent_data_provider.rs, toolkit/primitives/authority-selection-inherents/src/runtime_api_mock.rs, toolkit/primitives/session-manager/src/lib.rs, toolkit/primitives/session-manager/src/pallet_session_support.rs, toolkit/primitives/session-validator-management/Cargo.toml, toolkit/primitives/session-validator-management/query/Cargo.toml, toolkit/primitives/session-validator-management/query/src/get_registrations.rs, toolkit/primitives/session-validator-management/query/src/lib.rs, toolkit/primitives/session-validator-management/query/src/tests/mod.rs, toolkit/primitives/session-validator-management/query/src/tests/runtime_api_mock.rs, toolkit/primitives/session-validator-management/query/src/types/mod.rs, toolkit/primitives/session-validator-management/src/lib.rs
- Adds V2 methods in `SessionValidatorManagementApi` that `CommitteeMember` where possible.
- Updates `pallet-session-validator-management-query` to be version-aware
- Various updates in the test mocks required by the changes above
for you.
=> change: Update Validators Management Pallet's runtime API and RPC

dev/nix/shell.nix, flake.lock
* Upgrading nixpkgs recently broke `tikv-jemalloc-sys`, requiring a c flag to be turned on. (Thanks @gilligan)
* This PR also bumps fenix
for you.
=> fix jemalloc in nix

dev/nix/shell.nix, e2e-tests/README.md
This change extends the LD_LIBRARY_PATH to include libs required by numpy. This wouldn't be necessary if we were providing python packages through Nix but we aren't so we need to make them visible
=> Fix e2e python env in nix shell for linux

e2e-tests/src/substrate_api.py
fixes:
- stake key hash conversion to hex rairly could be broken if the leading number was 0
=> test: fix non hex number in address association test

node/node/src/tests/runtime_api_mock.rs, node/runtime/src/lib.rs, toolkit/pallets/block-production-log/src/lib.rs, toolkit/pallets/block-production-log/src/test.rs, toolkit/pallets/session-validator-management/src/lib.rs, toolkit/primitives/block-production-log/src/lib.rs, toolkit/primitives/block-production-log/src/test.rs
- if `LastBlock` is empty, the pallet's inherent is NOT required. it becomes required, once the storage is set.
- changes the `get_current_author` API method to return Option, and the InherentDataProvider
The rationale for this is to allow the pallet to be added as part of a wider runtime upgrade and avoid issues on the first block after the upgrade, caused by access to yet-unmigrated storages. This is achieved by treating the `LastBlock` as an initialized state flag.
for you.
=> change: require block production log pallet inherent only after data becomes available

.github/workflows/release.yml
changed:
- use inputs.sha instead of tag to checkout proper e2e-tests to avoid unnecessary release candidates
Refs: ETCM-9451
=> chore: avoid too many release candidates

changelog.md, docs/developer-guides/native-token-reserve-management.md, toolkit/cli/smart-contracts-commands/src/reserve.rs, toolkit/offchain/src/reserve/deposit.rs, toolkit/offchain/tests/integration_tests.rs
Removed `token` parameter from the `smart-contracts reserve deposit` command, because asset id is already present in the reserve settings.
Ref: ETCM-9243 (Point 1 & 3)
=> feat: simplify 'deposit' by removing token (asset id) parameter

.github/actions/tests/local-environment-tests/action.yml, .github/actions/tests/run-e2e-tests/action.yml, .github/workflows/ci.yml, .github/workflows/devnet.yml, .github/workflows/staging.yml, e2e-tests/.gitignore, e2e-tests/Earthfile, e2e-tests/pytest.ini, e2e-tests/report_slack.sh, e2e-tests/tests/conftest.py
added:
- when tests are ran in parallel, each thread stores log separately to not overwrite debug.log file
changed:
- all test logs are now stored in e2e-tests/logs dir
Refs: ETCM-9484
=> test: one log file per worker

changelog.md, docs/developer-guides/native-token-reserve-management.md, docs/user-guides/governance/governance.md, toolkit/cli/smart-contracts-commands/src/reserve.rs, toolkit/offchain/src/reserve/create.rs, toolkit/offchain/src/reserve/mod.rs, toolkit/offchain/tests/integration_tests.rs
* merges CLI command `reserve init` and `reserve create`
* makes `create` idempotent-ish (idempotent when settings are same)
* updates docs - there is some shuffling of docs in this PR, I'll revert if there are objections for it
Ref: ETCM-9243
=> Merge reserve init and create

.github/actions/tests/argocd-tests/action.yml, .github/actions/tests/run-e2e-tests/action.yml, .github/workflows/devnet.yml, .github/workflows/staging.yml, e2e-tests/Earthfile, e2e-tests/README.md, e2e-tests/docs/run-tests-on-local-env.md, e2e-tests/docs/run-tests-on-new-env.md, e2e-tests/tests/conftest.py
Removes --stack arg from E2E runner. Previously it made sense to have different --env and --stack but with the introduction of local-env this is no longer the case.
=> ETCM-9514 drop --stack arg from e2e runner

node/runtime/src/genesis_config_presets.rs, node/runtime/src/test_helper_pallet.rs
`participation_data_release_period` in `test_helper_pallet` does not have an explicit default, so it defaults to 0 (for example when upgrading the runtime). This causes test_helper_pallet to cause an execution failure because it is used on the right-hand side of a modulo operation.
This PR provides the default value of 30.
=> ETCM-9535 provide default for test_helper_pallet::participation_data_release_period

e2e-tests/secrets/substrate/staging/staging.json, e2e-tests/tests/smart_contracts/test_native_token.py
changed:
- `reserve init` was moved to its own test
- handle running native token tests multiple times on existing chain
- updated staging-services IP (matter only if running tests from localhost)
Refs: ETCM-9243
=> reserve-init-separate-test

.github/actions/tests/local-environment-tests/action.yml, e2e-tests/pytest.ini, e2e-tests/tests/smart_contracts/test_native_token.py
changed:
- post-merge CI action excludes native token tests because they're skipped (were executed earlier) and that was causing job to fail (we expect no skipped tests on last run
=> test: do not run native token on last post merge run

toolkit/partner-chains-cli/src/config.rs
This is for backwards compatibility with wizard config files from 1.5 and before.
=> fix: use default of 1000ms in start-node when slot_duration_missing (ETCM-9582)

e2e-tests/config/substrate/staging-ci.json, e2e-tests/config/substrate/staging_nodes.json, e2e-tests/src/substrate_api.py, e2e-tests/tests/committee/test_committee.py
added:
- staging validator-5 dns resolvable when run in CI
fixed:
- staging validators' ports
- `node smart-contracts` response handling after recent refactoring
- `test_update_d_param` could not be run on staging due to missing fixture to scp skey
=> test: fix staging validators' ports and smart-contracts response handling

toolkit/offchain/src/governance.rs, toolkit/offchain/src/permissioned_candidates.rs, toolkit/offchain/tests/integration_tests.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/tests/mod.rs, toolkit/primitives/domain/src/lib.rs
`upsert-permissioned-candidates` will return transaction cbor if the governance authority is not 1-of-1 for a payment key.
I cannot get this to test with multisig governance yet, because we don't have update governance implemented
Ref: https://input-output.atlassian.net/browse/ETCM-9500
=> feat: prepare upsert-permissioned-candidates for MultiSig

Cargo.lock, Cargo.toml, changelog.md, node/node/src/command/mod.rs, node/runtime/src/lib.rs, toolkit/cli/commands/Cargo.toml, toolkit/cli/commands/src/block_producer_metadata_signatures.rs, toolkit/cli/commands/src/key_params.rs, toolkit/cli/commands/src/lib.rs, toolkit/cli/node-commands/src/lib.rs, toolkit/primitives/block-producer-metadata/Cargo.toml, toolkit/primitives/block-producer-metadata/src/lib.rs, toolkit/primitives/domain/src/byte_string.rs
- adds a `sign-block-producer-metadata` command
- adds a `BoundedString` type for storing strings in the runtime
- adds a `BlockProducerMetadata` to the demo runtime, containing a URL bounded string and hash
=> add: ETCM-9596 block producer metadata singing command

.github/workflows/staging.yml
fixes:
- workflow_dispatch always uses master, but we checkout v1.6 to run nightly tests, and active_flow tests are still there and we were trying to run them generating a bunch of false positives
Refs: ETCM-9616
=> test: fix nightly running from branch

Cargo.lock, Cargo.toml, changelog.md, toolkit/mainchain-follower/db-sync-follower/Cargo.toml, toolkit/mainchain-follower/db-sync-follower/src/db_model.rs, toolkit/utils/db-sync-sqlx/Cargo.toml, toolkit/utils/db-sync-sqlx/src/lib.rs
Moves some db-sync types from `db-sync-follower` to a new crate `db-sync-sqlx`, so they can be more safely shared. These are only "primitive" types, because `db-sync-follower` types representing table rows do not have all columns.
=> add: ETCM-9618 db-sync-sqlx crate with db-sync primitive types

toolkit/partner-chains-cli/src/prepare_configuration/init_governance.rs, toolkit/partner-chains-cli/src/tests/mod.rs, toolkit/smart-contracts/commands/src/governance.rs, toolkit/smart-contracts/offchain/src/csl.rs, toolkit/smart-contracts/offchain/src/init_governance/mod.rs, toolkit/smart-contracts/offchain/src/init_governance/tests.rs, toolkit/smart-contracts/offchain/src/init_governance/transaction.rs, toolkit/smart-contracts/offchain/src/register.rs, toolkit/smart-contracts/offchain/src/update_governance/test.rs
* prefer `McTxHash` to `OgmiosTx`
* remove `OgmiosUtxoExt::to_domain()`, because it is available without extension trait as `::utxo_id()`
* return struct instead of tuple in governance init
* print json to stdout
=> refactor: don't use Ogmios types where domain types are enough

changelog.md, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/tests/mod.rs, toolkit/sidechain/domain/src/lib.rs, toolkit/smart-contracts/commands/src/governance.rs, toolkit/smart-contracts/commands/src/permissioned_candidates.rs, toolkit/smart-contracts/offchain/src/csl.rs, toolkit/smart-contracts/offchain/src/d_param/tests.rs, toolkit/smart-contracts/offchain/src/init_governance/mod.rs, toolkit/smart-contracts/offchain/src/init_governance/tests.rs, toolkit/smart-contracts/offchain/src/lib.rs, toolkit/smart-contracts/offchain/src/multisig.rs, toolkit/smart-contracts/offchain/src/permissioned_candidates.rs, toolkit/smart-contracts/offchain/src/register.rs, toolkit/smart-contracts/offchain/src/reserve/init.rs, toolkit/smart-contracts/offchain/src/reserve/release.rs, toolkit/smart-contracts/offchain/src/update_governance/mod.rs, toolkit/smart-contracts/offchain/src/update_governance/test.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
Implements temporary wallet to prevent spending Transaction Inputs while the transaction is being signed.
For now it simply sends 5 ADA to temporary wallet and it seems to be enough. Change is sent back to payment address.
Potentially something more sophisticated will be required for smart contracts that spend some MultiAssets from payment address - I'm looking at reserve create/deposit, but this will come later.
Other thing that is now apparent is that `TransactionContext` binds quite few items and is passed by reference. In principle any transaction submission makes it invalid, because the set of available UTXOs on Cardano differs. This PR does not solve this problem.
REF: ETCM-9576
=> feat: prevent spending transaction inputs by introducing temporary wallet

changelog.md, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/tests/mod.rs, toolkit/smart-contracts/commands/src/d_parameter.rs, toolkit/smart-contracts/offchain/src/d_param/mod.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
[link](https://input-output.atlassian.net/browse/ETCM-9518)
=> multi-sig for d-param

toolkit/sidechain/domain/src/byte_string.rs, toolkit/smart-contracts/offchain/src/assemble_tx.rs, toolkit/smart-contracts/offchain/src/csl.rs, toolkit/smart-contracts/offchain/src/d_param/mod.rs, toolkit/smart-contracts/offchain/src/governance.rs, toolkit/smart-contracts/offchain/src/init_governance/mod.rs, toolkit/smart-contracts/offchain/src/init_governance/tests.rs, toolkit/smart-contracts/offchain/src/init_governance/transaction.rs, toolkit/smart-contracts/offchain/src/multisig.rs, toolkit/smart-contracts/offchain/src/permissioned_candidates.rs, toolkit/smart-contracts/offchain/src/reserve/init.rs, toolkit/smart-contracts/offchain/src/reserve/release.rs, toolkit/smart-contracts/offchain/src/test_values.rs, toolkit/smart-contracts/offchain/src/update_governance/mod.rs, toolkit/smart-contracts/offchain/src/update_governance/test.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
* Estimation of required temporary wallet funds is updated from `5 ADA` to `(inputs - change) + 5 ADA`. Difference of inputs and change alone is not enough because of presence of unrelated multi-assets tokens is relevant. Maybe there are other factors that I have failed to identify. This works with all our smart-contracts in integration tests. I have all reserve operations working on other branch.
* Approx 10 clippy changes
REF: ETCM-9627
=> feat: estimate funds required for temporary wallet

changelog.md, substrate-extensions/partner-chains-session/src/lib.rs
This PR extends `pallet_partner_chains_session` with implementation of `FindAccountFromAuthorIndex` trait with small adjustment to use `ValidatorsAndKeys`. Code is almost entirely copy-pasted from original `pallet-session`.
This trait will be later used as part of other pallet integrations like `im-online`.
=> Added FindAccountFromAuthorIndex for pallet_partner_chains_session

changelog.md, toolkit/smart-contracts/offchain/src/csl.rs, toolkit/smart-contracts/offchain/src/init_governance/tests.rs, toolkit/smart-contracts/offchain/src/init_governance/transaction.rs, toolkit/smart-contracts/offchain/src/register.rs, toolkit/smart-contracts/offchain/src/test_values.rs
Scripts present in the inputs influence transaction cost. The bug was that `genesis_utxo` was added as "key input", and CSL (as documented) doesn't look for scripts and they don't affect the fee. Therefore Ogmios/Cardano node rejected transaction with insufficient fee.
REF: ETCM-9632
=> fix: use regular inputs, because key inputs lead to insufficient fee in case of scripts attached to UTXOs

.github/workflows/e2e-tests.yml
added:
- env dropdown in GH action to run tests against specific environment
=> chore: add GH action to run e2e-tests on ci-preview

dev/nix/shell.nix
Adds bashInteractive to nix shell. This fixes an issue with the embedded terminal of vscode.
=> add bashInteractive to dev shell

e2e-tests/config/api_config.py, e2e-tests/config/substrate/ci_nodes.json, e2e-tests/config/substrate/devnet_nodes.json, e2e-tests/config/substrate/local_nodes.json, e2e-tests/config/substrate/staging_nodes.json, e2e-tests/docs/run-tests-on-new-env.md, e2e-tests/pytest.ini, e2e-tests/requirements.txt, e2e-tests/src/blockchain_api.py, e2e-tests/src/cardano_cli.py, e2e-tests/src/substrate_api.py, e2e-tests/tests/committee/conftest.py, e2e-tests/tests/committee/test_blocks.py, e2e-tests/tests/conftest.py, e2e-tests/tests/delegator_rewards/conftest.py, e2e-tests/tests/delegator_rewards/test_block_production_log.py, e2e-tests/tests/delegator_rewards/test_delegator_journey.py, e2e-tests/tests/delegator_rewards/test_spo_journey.py, e2e-tests/tests/test_delegator_rewards.py, e2e-tests/utils/pc_epoch_calc.py
added:
- new test for delegator rewards in `test_delegator_rewards.py` 
to verify raw inherent data
changed:
- refactored `get_stake_pool_id` method in `cardano_cli.py` to simplify its parameters
- moved all delegator rewards tests into the same directory
removed:
- `block_rewards_id` config field has been removed
=> delegator-rewards-e2e-tests

demo/node/src/cli.rs, demo/node/src/command/mod.rs, toolkit/cli/node-commands/src/lib.rs
We unnecessarily hard-coded `AccountId32` for Address Associations in `partner-chains-node-commands`.
This PR replaces it with a generic type.
=> change: make Partner Chain address used by node-commands generic

e2e-tests/src/partner_chains_node/node.py, e2e-tests/src/run_command.py, e2e-tests/tests/committee/test_blocks.py, e2e-tests/tests/delegator_rewards/test_spo_journey.py
fixes:
- delegator rewards tests may fail if delegators had 0 stake
- `test_block_producer_can_update_their_metadata` was failing on non local-env due to incorrect escaping
=> test(fix): query delegators with non-zero stake

.github/workflows/ci.yml, Earthfile, dev/local-environment/setup.sh
Successful pre-merge CI run test:
https://github.com/input-output-hk/partner-chains/actions/runs/14308332981
Package repository created:
https://github.com/input-output-hk/partner-chains/pkgs/container/partner-chains%2Fpartner-chains-node-unstable
=> feat: CI post-merge pushes to new partner-chains-node-unstable GHCR repository

toolkit/cli/commands/Cargo.toml, toolkit/cli/node-commands/Cargo.toml, toolkit/mainchain-follower/db-sync-follower/Cargo.toml, toolkit/pallets/session-validator-management/rpc/Cargo.toml, toolkit/pallets/sidechain/rpc/Cargo.toml, toolkit/primitives/plutus-data/Cargo.toml, toolkit/primitives/session-validator-management/query/Cargo.toml, toolkit/primitives/sidechain-block-search/Cargo.toml
This ports https://github.com/input-output-hk/partner-chains/pull/660 to 1.5.1
=> change: remove default features from workspace crates (1.5.1)

toolkit/cli/commands/Cargo.toml, toolkit/cli/node-commands/Cargo.toml, toolkit/mainchain-follower/db-sync-follower/Cargo.toml, toolkit/pallets/session-validator-management/rpc/Cargo.toml, toolkit/pallets/sidechain/rpc/Cargo.toml, toolkit/primitives/plutus-data/Cargo.toml, toolkit/primitives/session-validator-management/query/Cargo.toml, toolkit/primitives/sidechain-block-search/Cargo.toml
This ports https://github.com/input-output-hk/partner-chains/pull/660 to 1.6.1
=> change: avoid using default features (1.6.1)

toolkit/smart-contracts/offchain/src/governed_map/mod.rs, toolkit/smart-contracts/offchain/src/governed_map/tests.rs
This causes the offchain to not fail if some utxos contain datums that do not conform to the expected schema and instead to ignore those datums completely.
=> fix: Ignore decoding errors when filtering governed map utxos

dev/nix/shell.nix
On macOS, the error "failed to run custom build command for `wasm-opt-sys v0.116.0`" exists because of the way cc-rs detects whether a compiler supports std=c++17, it doesn't detect it available and compilation fails. This commit disables the check.
to the issue.
=> fix(devshell): disable compiler check on cc-rs

toolkit/smart-contracts/commands/src/governed_map.rs, toolkit/smart-contracts/offchain/src/governed_map/mod.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
Adds the `smart-contracts governed-map list` command and wires it into the demo node.
Output:
```json
[{"key":"key1","value":"0xaaaabbbb0000"},{"key":"key2","value":"0x01"}]
```
=> add: ETCM-9697 Governed Map list command

changelog.md, toolkit/smart-contracts/commands/src/governed_map.rs, toolkit/smart-contracts/offchain/src/csl.rs, toolkit/smart-contracts/offchain/src/governed_map/mod.rs, toolkit/smart-contracts/offchain/src/governed_map/tests.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
[link](https://input-output.atlassian.net/browse/ETCM-9696)
The remove command should spend all utxos with the given key if multiple are found. I'm kind of worried about this, becasue  this is the first time we have transaction that spends more than one utxo from script address. If my assumption about how cost models will behave is correct, this PR should be ok, and we should not worry. I've added test that does remove when there are 2 utxos with the same key, but I'm still kind of worried, that it might break down in some real life scenario.
=> add governed-map remove command

toolkit/smart-contracts/commands/src/governed_map.rs, toolkit/smart-contracts/offchain/src/governed_map/mod.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
Adds `smart-contracts governed-map get` command that retrieves value for given key in the Governed Map.
Output when there's data:
```json
"0xaabbcc"
```
Output when the key is unset:
```json
{}
```
=> add: ETCM-9698 Governed Map get command

toolkit/smart-contracts/commands/src/d_parameter.rs, toolkit/smart-contracts/commands/src/get_scripts.rs, toolkit/smart-contracts/commands/src/governance.rs, toolkit/smart-contracts/commands/src/governed_map.rs, toolkit/smart-contracts/commands/src/lib.rs, toolkit/smart-contracts/commands/src/permissioned_candidates.rs, toolkit/smart-contracts/commands/src/register.rs, toolkit/smart-contracts/commands/src/reserve.rs
'g' was used for governed map. I propose to use a type for genesis-utxo parameter.
It is intentional to not use it in `governance init`, because it I think it should have a different help message in that context.
=> fix: use 'c' as short for 'genesis-utxo' parameter

toolkit/partner-chains-cli/src/deregister/mod.rs, toolkit/partner-chains-cli/src/deregister/tests.rs, toolkit/partner-chains-cli/src/lib.rs, toolkit/partner-chains-cli/src/prepare_configuration/init_governance.rs, toolkit/partner-chains-cli/src/prepare_configuration/mod.rs, toolkit/partner-chains-cli/src/register/register3.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/mod.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/tests/mod.rs, toolkit/smart-contracts/commands/src/assemble_tx.rs, toolkit/smart-contracts/commands/src/d_parameter.rs, toolkit/smart-contracts/commands/src/governance.rs, toolkit/smart-contracts/commands/src/governed_map.rs, toolkit/smart-contracts/commands/src/lib.rs, toolkit/smart-contracts/commands/src/permissioned_candidates.rs, toolkit/smart-contracts/commands/src/register.rs, toolkit/smart-contracts/commands/src/reserve.rs, toolkit/smart-contracts/offchain/src/assemble_tx.rs, toolkit/smart-contracts/offchain/src/d_param/mod.rs, toolkit/smart-contracts/offchain/src/governed_map/mod.rs, toolkit/smart-contracts/offchain/src/init_governance/mod.rs, toolkit/smart-contracts/offchain/src/permissioned_candidates.rs, toolkit/smart-contracts/offchain/src/register.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
Adds command line arguments to allow setting retry parameters, while preserving the currently set defaults.
=> Add cmd line args for configuring retry params

changelog.md, toolkit/partner-chains-cli/src/prepare_configuration/select_genesis_utxo.rs
When running `prepare-configuration` with config file already containing `chain_parameters.genesis_utxo`, the value of the field was not updated with the new UTXO
REF: ETCM-9786
=> fix: make prepare-configuration update genesis_utxo in pc-chain-config.json

.github/actions/deploy/deploy-rustdoc/action.yml, dev/nix/shell.nix
This changes the rust-doc CI job to build docs using nightly cargo which supports `--enable-index` creating an index.html that links to all crates.
Cargo is provided via small addition in shell.nix providing nightly in a devShell of the same name.
=> Nightly cargo docs

toolkit/committee-selection/selection/src/ariadne.rs, toolkit/committee-selection/selection/src/ariadne_v2.rs, toolkit/committee-selection/selection/src/lib.rs, toolkit/committee-selection/selection/src/tests.rs, toolkit/committee-selection/selection/src/weighted_random.rs
- Adds documentation and makes it requires in `selection` crate
- Removes the unneeded `WeightedRandomSelectionConfig` struct
- moves weighted-random tests into its module
=> change: Document and clean up the selection crate

.github/workflows/ci.yml
The rustdoc ci action uses nix and needs to be executed no nixos
=> ci: run cargo doc on nixos

Cargo.lock, demo/node/src/data_sources.rs, demo/node/src/inherent_data.rs, demo/node/src/tests/runtime_api_mock.rs, demo/runtime/src/lib.rs, toolkit/data-sources/db-sync/Cargo.toml, toolkit/data-sources/db-sync/src/governed_map/mod.rs, toolkit/data-sources/db-sync/src/governed_map/tests.rs, toolkit/data-sources/db-sync/testdata/governed-map/migrations/1_create_schema.sql, toolkit/data-sources/db-sync/testdata/governed-map/migrations/2_data.sql, toolkit/data-sources/mock/src/governed_map.rs, toolkit/governed-map/primitives/src/lib.rs, toolkit/governed-map/primitives/src/mock.rs, toolkit/governed-map/primitives/src/tests.rs
* Redefines the `GovernedMapDataSource` to provide the list of mapping changes in a given block range instead of full state at block and rewrites the implementations to conform to it
* Rewrites the `GovernedMapInherentDataProvider` to operate on changes too
=> change: ETCM-9783 Rework the Governed Map IDP and data source API to operate on change lists

Cargo.lock, Cargo.toml, changelog.md, demo/runtime/Cargo.toml, demo/runtime/src/lib.rs, toolkit/block-participation/pallet/src/mock.rs, toolkit/block-producer-fees/pallet/Cargo.toml, toolkit/block-producer-fees/pallet/src/lib.rs, toolkit/block-producer-fees/pallet/src/mock.rs, toolkit/block-producer-fees/pallet/src/tests.rs, toolkit/block-producer-fees/pallet/src/weights.rs, toolkit/block-producer-fees/readme.md
Adds `block-producer-fees` pallet.
Requirements were trimmed down to one setting for margin fee, that should be in range between 0% and 100%, with precision of 1/100th of a percent.
The configurable number of historical items and storing the slot of a change is added to satisfy requirements:
* "Changes to the fee in epoch n MUST take effect in epoch n+1" - rewards will be able to use value that is not the latest
* "There must be a mechanism that allows for delegators to be notified of a change in margin fee"
RPC and benchmarking will be done separately.
Ticket with requirements: https://input-output.atlassian.net/browse/ETCM-9326
=> feat: add block producer fees pallet

toolkit/smart-contracts/commands/src/governed_map.rs
This PR changes the output of governed map commands:
- When no TX is submitted we return `{}` instead of `null`
=> Governed map commands return {} instead of null

toolkit/smart-contracts/offchain/src/scripts_data.rs
=> chore: rename generic_container leftovers to governed_map

demo/node/src/data_sources.rs, toolkit/data-sources/db-sync/src/block/mod.rs, toolkit/data-sources/db-sync/src/db_model.rs, toolkit/data-sources/db-sync/src/governed_map/mod.rs, toolkit/data-sources/db-sync/src/governed_map/tests.rs, toolkit/governed-map/primitives/src/lib.rs, toolkit/utils/db-sync-sqlx/src/lib.rs
[link](https://input-output.atlassian.net/browse/ETCM-9734)
Adds Cached GovernedMap DataSource implementation, and uses it in demo-node
=> add: ETCM-9734 caching for governed map data

Cargo.lock, demo/node/src/data_sources.rs, demo/runtime/src/lib.rs, toolkit/data-sources/db-sync/src/governed_map/mod.rs, toolkit/data-sources/mock/src/governed_map.rs, toolkit/governed-map/pallet/src/benchmarking.rs, toolkit/governed-map/pallet/src/lib.rs, toolkit/governed-map/pallet/src/tests.rs, toolkit/governed-map/primitives/Cargo.toml, toolkit/governed-map/primitives/src/lib.rs, toolkit/governed-map/primitives/src/mock.rs, toolkit/governed-map/primitives/src/tests.rs
* Correctly handles changing main chain scripts by tracking "initialized" state in the pallet and resetting it on script change
* Modifes the IDP to work differently for initialized and uninitialized pallet state:
* uninitialized: fetches full Governed Map state, compares it with the pallet's storage and provides the changes as inherent data. This is necessary when the pallet needs to be re-initialized after main chain script change, but it already contains some data.
* initialized: only fetches changes since last MC hash and provides them as inherent data
* Modifies the runtime API to also provide initialization status and current mappings
* Modifies the data source API to provide methods to both 1) query full state at block; 2) query changes between blocks
* Uses BTreeMap for changes in …
=> change: ETCM-9800 track and handle initialization of the governed map pallet

dev/local-environment/envrc, toolkit/data-sources/db-sync/src/db_model.rs, toolkit/data-sources/db-sync/src/governed_map/mod.rs
Fixes an issue where our query for changes in the governed map would sometimes put utxo spend event before new utxo creation, resulting in an updated key being interpreted as deleted.
=> fix: ETCM-9836 governed map changes query

dev/nix/shell.nix
The nightly rust toolchain and the gen-docs wrapper aren't used anymore
=> Drop nightly rust from shell.nix

Cargo.lock, Cargo.toml, demo/node/Cargo.toml, demo/node/src/rpc.rs, demo/runtime/Cargo.toml, demo/runtime/src/lib.rs, toolkit/block-producer-fees/pallet/Cargo.toml, toolkit/block-producer-fees/pallet/src/lib.rs, toolkit/block-producer-fees/primitives/Cargo.toml, toolkit/block-producer-fees/primitives/src/lib.rs, toolkit/block-producer-fees/rpc/Cargo.toml, toolkit/block-producer-fees/rpc/src/lib.rs, toolkit/block-production-log/primitives/src/lib.rs
* Adds RPC method to retrieve current fees settings
```
curl -s -H "Content-Type:application/json" -d '{"jsonrpc":"2.0","method":"pc_getBlockProducerFees","params":[],"id":1}' localhost:9933 | jq .result
[
{
"account_id": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
"margin_fee": 10.0
},
{
"account_id": "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
"margin_fee": 1.25
}
]
```
REF: ETCM-9326
=> feat: add pc_getBlockProducerFees RPC method

toolkit/committee-selection/query/src/lib.rs
Slightly more descriptive error message in case that `sidechain_getEpochCommittee` is executed on non-archive node.
=> Extended error description in case node does not have enough history

Cargo.lock, changelog.md, demo/node/src/lib.rs, demo/node/src/main.rs, demo/runtime/src/lib.rs, toolkit/cli/commands/Cargo.toml, toolkit/cli/commands/src/get_genesis_utxo.rs, toolkit/cli/commands/src/lib.rs, toolkit/cli/node-commands/src/lib.rs, toolkit/committee-selection/query/src/lib.rs, toolkit/committee-selection/query/src/tests/mod.rs, toolkit/committee-selection/query/src/tests/runtime_api_mock.rs, toolkit/sidechain/primitives/Cargo.toml, toolkit/sidechain/primitives/src/lib.rs, toolkit/sidechain/rpc/src/lib.rs, toolkit/sidechain/rpc/src/tests/mod.rs, toolkit/sidechain/rpc/src/tests/rpc_mock.rs, toolkit/sidechain/rpc/src/tests/runtime_api_mock.rs, toolkit/sidechain/sidechain-block-search/src/impl_block_info.rs, toolkit/sidechain/sidechain-block-search/src/lib.rs, toolkit/sidechain/sidechain-block-search/src/tests/runtime_api_mock.rs
- Moves the logic in `query` module out of the crate completely. It contained a json-string-returning function used on only by a CLI command, which the primitives should not know anything about, and an output struct shared between rpc and cli, which they should not share
- Deprecates the `GetSidechainStatus` runtime API and its returned type `SidechainStatus` (and removes some unnecessary uses of it). This API is mis-named (doesn't serve any status), returns a structure out of which each user code needs only one field, and one field is not used at all. Ideally, each functionality should define the runtime API it consumes instead of sharing one with other unrelated functionalities.
=> change: Sidechain primitives crates cleanup

changelog.md, toolkit/partner-chains-cli/src/config.rs, toolkit/partner-chains-cli/src/create_chain_spec/mod.rs, toolkit/partner-chains-cli/src/create_chain_spec/tests.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/sidechain/domain/Cargo.toml
This updates governedMap.MainChainScripts in the same way as initial validators are set and differently to how other MainChainScripts are set.
This is intentionally ditching reliance on the node `chain-spec` command, and in turn its reliance on env variables.
Please read questions in the comments.
=> feat: make wizards set governedMap.MainChainScripts in the chain-spec file

changelog.md, demo/node/src/data_sources.rs, demo/node/src/service.rs, toolkit/data-sources/cli/src/main.rs, toolkit/data-sources/db-sync/src/block/mod.rs, toolkit/data-sources/db-sync/src/candidates/datum.rs, toolkit/data-sources/db-sync/src/candidates/mod.rs, toolkit/data-sources/db-sync/src/data_sources.rs, toolkit/data-sources/db-sync/src/governed_map/mod.rs, toolkit/data-sources/db-sync/src/lib.rs, toolkit/data-sources/db-sync/src/mc_hash/mod.rs, toolkit/data-sources/db-sync/src/metrics.rs, toolkit/data-sources/db-sync/src/native_token/mod.rs, toolkit/data-sources/db-sync/src/sidechain_rpc/mod.rs, toolkit/data-sources/db-sync/src/stake_distribution/mod.rs
- Documents the `partner-chains-db-sync-data-sources` crate
- Fixes visibility of some members that should not be public
- Simplifies some code using already existing helpers
- Re-exports all public members of the crate from its root and makes individual modules private, so they're easier to import
=> change: ETCM-9687 small fixes and docs for db-sync data sources crate

toolkit/partner-chains-cli/src/io.rs
ECS pressed:
```
./partner-chains-demo-node wizards prepare-configuration
This 🧙 wizard will generate chain config file
? node base path <canceled>
```
Ctrl-C:
```
./partner-chains-demo-node wizards prepare-configuration
This 🧙 wizard will generate chain config file
? node base path (./data)
Ctrl-C pressed. Exiting Wizard.
```
REF: ETCM-11879
=> feat: handle Ctrl-C and ESC in wizards without panic

toolkit/committee-selection/selection/src/ariadne_v2.rs
Node is not sorting registered candidates and it never was doing it.
Ariadne v1 was sorting them. Ariadne v2 was not. This fixes this missing sorting in Ariadne v2.
ETCM-11891
=> fix: sort candidates inside ariadne_v2, to make it tolerant for unsorted inputs

toolkit/partner-chains-cli/src/cmd_traits.rs, toolkit/partner-chains-cli/src/deregister/mod.rs, toolkit/partner-chains-cli/src/deregister/tests.rs, toolkit/partner-chains-cli/src/io.rs, toolkit/partner-chains-cli/src/lib.rs, toolkit/partner-chains-cli/src/permissioned_candidates.rs, toolkit/partner-chains-cli/src/prepare_configuration/init_governance.rs, toolkit/partner-chains-cli/src/prepare_configuration/mod.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/register/mod.rs, toolkit/partner-chains-cli/src/register/register3.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/mod.rs, toolkit/partner-chains-cli/src/tests/mod.rs, toolkit/smart-contracts/offchain/src/d_param/mod.rs, toolkit/smart-contracts/offchain/src/init_governance/mod.rs, toolkit/smart-contracts/offchain/src/lib.rs, toolkit/smart-contracts/offchain/src/permissioned_candidates.rs, toolkit/smart-contracts/offchain/src/register.rs, toolkit/smart-contracts/offchain/src/scripts_data.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
`smart-contracts/offchain` provides traits that are used for mocking calls to offchain commands in `partner-chains-cli` testing. Since the traits are not used anywhere else it makes more sense for `partner-chains-cli` to provide them.
=> chore: move offchain command traits

docs/intro.md
Adds documentation of all pc cli commands
=> add docs for cli commands

flake.nix
Fix numpy compile problems:
Adding stdenv.cc.c to the LIBRARY_PATH is necessary to make NumPy happy which otherwise fails when trying to run the e2e tests
=> Fix python setup

toolkit/utils/ogmios-client/src/jsonrpsee.rs
Overrides default 10 MB max response size. This is order to not fail when there are many UTXOs at the registrations validator address.
Before:
```
./target/debug/partner-chains-demo-node smart-contracts register ...
2025-06-13T09:37:35.347745439+02:00 WARN soketto::connection - b6ca6eaa: accumulated message length exceeds maximum
Error: Application(JsonRPC request failed: 'The background task closed message too large: len >= 14705278, maximum = 10485760; restart required')
```
After:
```
./target/debug/partner-chains-demo-node smart-contracts register ...
2025-06-13T09:43:33.113725973+02:00 INFO partner_chains_cardano_offchain::register - ✅ Transaction submitted. ID: 977bfa7a5cf1e5d5805962e2ea0c2d2189ddf175df5e6c6e503ebe604177ce2a
```
REF: ETCM-9399
=> feat: do not fail on 10MB Ogmios responses

changelog.md, dev/local-environment/configurations/wizard/governance-authority/entrypoint.sh, docs/user-guides/chain-builder.md, toolkit/partner-chains-cli/src/config.rs, toolkit/partner-chains-cli/src/create_chain_spec/mod.rs, toolkit/partner-chains-cli/src/create_chain_spec/tests.rs, toolkit/partner-chains-cli/src/deregister/tests.rs, toolkit/partner-chains-cli/src/generate_keys/tests.rs, toolkit/partner-chains-cli/src/lib.rs, toolkit/partner-chains-cli/src/ogmios/config.rs, toolkit/partner-chains-cli/src/prepare_configuration/init_governance.rs, toolkit/partner-chains-cli/src/prepare_configuration/mod.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/prepare_configuration/select_genesis_utxo.rs, toolkit/partner-chains-cli/src/register/register1.rs, toolkit/partner-chains-cli/src/register/register3.rs
This allows to run `prepare-configuration` without running `generate-keys`, making generation of keys optional.
Also, recommended order of running wizards has changed, moving `setup-main-chain-state` before `create-chain-spec`, although both can be run independently.
=> feat: make setting bootnodes optional in `prepare-configuration`

toolkit/smart-contracts/offchain/src/plutus_script.rs, toolkit/smart-contracts/offchain/src/reserve/release.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs, toolkit/smart-contracts/plutus-data/src/reserve.rs
* fix ICS UTXO being created with incorrect datum in `reserve release` command
* fix typos
* add ICS redeemer type (will be needed in the future)
* improves `plutus_scripts!` macro: it explicitly specifies the error type as `anyhow::Error` since that's what `apply_data_uplc` returns anyways, and this lets one write `plutus_script![SOME_SCRIPT]` without anything being applied.
=> Reserve release datum fix

changelog.md, dev/local-environment/configurations/partner-chains-setup/entrypoint.sh, dev/update-chain-spec.sh, toolkit/sidechain/domain/src/lib.rs
Modifies serialization of `MainchainAddress` to be plain string instead of hexstring of wrapped bytes. Deserialization handles both formats.
=> feat: serialize MainchainAddress as String, deserialize String and hexstring

toolkit/partner-chains-cli/Cargo.toml, toolkit/partner-chains-cli/src/config.rs, toolkit/partner-chains-cli/src/create_chain_spec/mod.rs, toolkit/partner-chains-cli/src/create_chain_spec/tests.rs, toolkit/partner-chains-cli/src/deregister/tests.rs, toolkit/partner-chains-cli/src/permissioned_candidates.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/register/register3.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/sidechain/domain/src/lib.rs
Adds types to the chain config.
Preliminary work for creating chain spec from wizards, without calling `node-executable build-spec`.
=> refactor: use types in CreateChainSpecConfig

changelog.md, toolkit/partner-chains-cli/src/config.rs, toolkit/partner-chains-cli/src/create_chain_spec/mod.rs, toolkit/partner-chains-cli/src/create_chain_spec/tests.rs, toolkit/partner-chains-cli/src/deregister/mod.rs, toolkit/partner-chains-cli/src/deregister/tests.rs, toolkit/partner-chains-cli/src/generate_keys/tests.rs, toolkit/partner-chains-cli/src/io.rs, toolkit/partner-chains-cli/src/prepare_configuration/init_governance.rs, toolkit/partner-chains-cli/src/prepare_configuration/mod.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_cardano_params.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/prepare_configuration/select_genesis_utxo.rs, toolkit/partner-chains-cli/src/register/register1.rs, toolkit/partner-chains-cli/src/register/register3.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/mod.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/start_node/mod.rs, toolkit/partner-chains-cli/src/start_node/tests.rs, toolkit/partner-chains-cli/src/tests/config.rs, toolkit/partner-chains-cli/src/tests/mod.rs
By popular demand this PR adds option to configure wizards Chain Config File and Resources Config File paths by using `PC_CHAIN_CONFIG_PATH` and `PC_RESOURCES_CONFIG_PATH` environment variables.
In case of their absence, the default values are used.
REF: ETCM-12090
=> feat: make Chain Config File and Resources Config File configurable by env vars

demo/node/src/chain_spec.rs, demo/node/src/service.rs, toolkit/block-producer-fees/rpc/src/lib.rs, toolkit/block-producer-metadata/pallet/src/benchmarking.rs, toolkit/committee-selection/authority-selection-inherents/src/authority_selection_inputs.rs, toolkit/committee-selection/authority-selection-inherents/src/lib.rs, toolkit/committee-selection/pallet/src/lib.rs, toolkit/committee-selection/pallet/src/migrations/v1.rs, toolkit/committee-selection/primitives/src/lib.rs, toolkit/data-sources/mock/src/lib.rs, toolkit/governed-map/pallet/src/lib.rs, toolkit/native-token-management/pallet/src/lib.rs, toolkit/native-token-management/primitives/src/lib.rs, toolkit/partner-chains-cli/src/create_chain_spec/mod.rs, toolkit/sidechain/domain/src/lib.rs, toolkit/sidechain/pallet/src/lib.rs, toolkit/sidechain/rpc/src/lib.rs, toolkit/sidechain/rpc/src/types/sidechain.rs, toolkit/smart-contracts/commands/src/lib.rs, toolkit/smart-contracts/offchain/src/plutus_script.rs, toolkit/smart-contracts/plutus-data/Cargo.toml, toolkit/smart-contracts/plutus-data/src/d_param.rs, toolkit/smart-contracts/plutus-data/src/lib.rs, toolkit/smart-contracts/plutus-data/src/permissioned_candidates.rs, toolkit/utils/ogmios-client/src/lib.rs, toolkit/utils/time-source/src/lib.rs
Fixes docs warnings in `cargo doc --no-deps`. Usually fixed by qualifying (scoping) type. See comments in the PR changes.
=> docs: fix warnings

toolkit/data-sources/db-sync/testdata/migrations/6_insert_transactions.sql, toolkit/sidechain/domain/src/lib.rs, toolkit/smart-contracts/plutus-data/src/permissioned_candidates.rs, toolkit/smart-contracts/plutus-data/src/registered_candidates.rs, toolkit/utils/db-sync-sqlx/src/lib.rs
* Change of v1 format for permissioned candidates - it's not too late, because nothing was writing it yet
* Implemented logic for writing: if keys are AURA and Grandpa only, then use v0, but if keys are different, then use v1
=> feat: write plutus data v1 for permissioned candidates and registrations

demo/runtime/src/lib.rs, e2e-tests/src/partner_chains_node/node.py, e2e-tests/src/substrate_api.py, e2e-tests/tests/committee/test_blocks.py, toolkit/block-producer-metadata/pallet/Cargo.toml, toolkit/block-producer-metadata/pallet/src/benchmarking.rs, toolkit/block-producer-metadata/pallet/src/lib.rs, toolkit/block-producer-metadata/pallet/src/mock.rs, toolkit/block-producer-metadata/pallet/src/tests.rs, toolkit/block-producer-metadata/primitives/src/lib.rs, toolkit/cli/commands/src/block_producer_metadata_signatures.rs, toolkit/cli/node-commands/src/lib.rs
* Adds `AccountId` of the extrinsic submitter to the signed message for updating block producer metadata to prevent front-run attacks
* Reworks the tests and benchmarks for the metadata pallet, so that signatures are now automatically signed instead of requiring manual updating using the CLI
=> fix: metadata extrinsic front-run attack, rework benchmarks

toolkit/cli/commands/src/address_association_signatures.rs, toolkit/cli/commands/src/block_producer_metadata_signatures.rs, toolkit/cli/node-commands/src/lib.rs, toolkit/sidechain/domain/src/lib.rs, toolkit/smart-contracts/commands/src/assemble_tx.rs, toolkit/smart-contracts/commands/src/lib.rs, toolkit/smart-contracts/commands/src/permissioned_candidates.rs, toolkit/smart-contracts/commands/src/register.rs, toolkit/smart-contracts/commands/src/sign_tx.rs
`clap` allows use of `value_parser` to specify what function should be used over the `FromStr` instance of a type when parsing command line arguments. In many cases we unnecessarily use this feature when a `FromStr` instance exists.
When the `FromStr` instance for a type has an `Err` type defined that does not convert to StdErr + etc as expected by clap it generates a confusing macro compile error which seems to have been worked around with custom `value_parser`s. To fix this a `FromStrStdErr` trait (quasi trait alias) is now provided that can be used when the struct used with `clap::Parser` has type params.
The parser for `PermissionedCandidateData` has been moved into a `FromStr` instance.
=> Remove custom clap parser functions

demo/runtime/src/genesis_config_presets.rs, e2e-tests/config/substrate/ci_nodes.json
* Additional epoch change, because today ci-preview was down for few hours
* removes redundant parentheses
=> fix post-merge CI errors

toolkit/data-sources/db-sync/src/db_model.rs, toolkit/data-sources/db-sync/src/lib.rs, toolkit/data-sources/db-sync/testdata/native-token/migrations/2_data.sql
Before the left join was counting in also other tokens transfer.
I've adjusted test data for this case by making irrelevant token transfer to the validator address.
EXPLAIN ANALYZE that I have run for ci-preview addresses and huge blocks range shown that this query is cheaper than the previous one.
=> bugfix: do not count irrelevant tokens transfer to ICS validator count

Cargo.lock, Cargo.toml, toolkit/data-sources/db-sync/Cargo.toml, toolkit/data-sources/db-sync/src/lib.rs, toolkit/smart-contracts/offchain/Cargo.toml, toolkit/smart-contracts/offchain/tests/integration_tests.rs
Update of testcontainers was not easy because the new version made it hard to stop the container in `dtor` annotated function. A lot of extra code is required to not get error about tokio thread local being destroyed.
I've tested this solution multiple time and there is no container left in my docker after tests are run.
=> Update testcontainers to 0.25.0

toolkit/data-sources/db-sync/src/bridge/mod.rs, toolkit/data-sources/db-sync/src/bridge/tests.rs, toolkit/data-sources/db-sync/src/db_model.rs, toolkit/data-sources/db-sync/testdata/bridge/migrations-tx-in-consumed/6_insert_transactions.sql, toolkit/data-sources/db-sync/testdata/bridge/migrations-tx-in-enabled/6_insert_transactions.sql
Fixes two issues:
1. Joining `datum` table on incorrect column
2. Reads the datum as optional and treats datum-less utxos with token as invalid transfers
=> fix: Datum handling in bridge data source

toolkit/data-sources/db-sync/src/bridge/cache.rs, toolkit/data-sources/db-sync/src/bridge/mod.rs, toolkit/data-sources/db-sync/src/db_model.rs, toolkit/smart-contracts/offchain/src/bridge/mod.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
Some follow ups for the db-sync data source for the bridge:
- renamed `BridgeCheckpoint` to `ResolvedBridgeDataCheckpoint`
- renamed and specialized the functions used when creating `ResolvedBridgeDataCheckpoint` to already return this type
- merged the two `tx-in` variants of the query into single function, as there's only one section that is different (this query will be further simplified if/when we get rid of the non-cached data source)
=> change: Bridge data sources code improvements

e2e-tests/src/partner_chains_node/smart_contracts.py, e2e-tests/tests/reserve/test_reserve_management.py, toolkit/smart-contracts/commands/src/bridge.rs, toolkit/smart-contracts/commands/src/lib.rs, toolkit/smart-contracts/offchain/src/bridge/create_utxos.rs, toolkit/smart-contracts/offchain/src/bridge/deposit.rs, toolkit/smart-contracts/offchain/src/bridge/init.rs, toolkit/smart-contracts/offchain/src/bridge/mod.rs, toolkit/smart-contracts/offchain/src/lib.rs, toolkit/smart-contracts/offchain/src/scripts_data.rs, toolkit/smart-contracts/offchain/src/versioning_system.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
This PR:
* adds command `bridge init` to initialize ICS Validator and ICS Auth Policy scripts in Versioning System
* adds command `bridge create` to create UTXOs at ICS Validator (it requires `init` to be executed first, so it cannot be done during `init`).
* renames `bridge` to `bridge deposit`
* adds `token` parameter to `bridge deposit`, so token AssetId is not read from reserve settings
This PR does not (there will be follow up):
* remove duplicated code
* remove initialization of ICS Validator nor ICS Auth Policy from `reserve init`
* remove creating UTXOs at ICS Validator
=> Split ICS (bridge) from reserve init and create - Part 1

toolkit/partner-chains-cli/src/create_chain_spec/mod.rs
I've found out that example in CLI output is syntactically invalid. Fixing it.
=> fix: make example initial authorities valid

dev/local-environment/configurations/partner-chains-setup/entrypoint.sh, toolkit/committee-selection/pallet/src/lib.rs, toolkit/committee-selection/pallet/src/pallet_session_support.rs
Properly adds an account provider and registers keys for all committee members when starting their session; removes account provider and deregisters keys for block producers that are no longer committee members.
=> change: Correct handling of provided accounts for block producers

changelog.md, demo/runtime/src/lib.rs, e2e-tests/tests/committee/test_committee.py, toolkit/committee-selection/pallet/src/lib.rs, toolkit/committee-selection/pallet/src/mock.rs, toolkit/committee-selection/pallet/src/pallet_session_support.rs
Currently we do 1-to-1 session and committee rotation. We select the next committee at some point of time, and when PC epoch changes, we end session, then on new session we rotate committee (this triggers selection of the committee at the next block) and pass the new committee to pallet_session. Pallet session queues new committee keys to be used in the next session. So, effectively there is a session and a block (~= partner chain epoch) delay between when according to our rules we would like to allow block production and when it happens.
Changes in this PR cause additional session end at the first block of a session caused by epoch boundary.
This effectively reduces the delay to two blocks
=> Start an additional session to accelerate usage of the new committee

dev/local-environment/setup.sh
Local env setup did not set CPU/MEM values for dolos env vars if interactive mode was used.
=> add missing dolos cpu/mem limits in interactive localenv setup
