input-output-hk/partner-chains

README.md, docs/user-guides/chain-builder.md
=> docs: fix: links

docs/user-guides/chain-builder.md, docs/user-guides/permissioned.md, docs/user-guides/registered.md
Update user guides to correct cardano-node version
=> docs: update version

scripts/echo_kubernetes_yamls.sh
Removed file has no use since moving parameters from runtime config to chain spec.
for you.
=> chore: remove unused echo-kubernetes-yamls.sh 

docs/developer-guides/dependencies.md, docs/developer-guides/getting-started.md
Reviving internal developer guides from the archived repo.
=> add dev guides

changelog.md
=> chore: update changelog for release candidate v1.1.0-rc2

.github/workflows/nix.yml
This adds a dispatch and a step in the nix building workflows that allows for checking against PRs opened in smart-contracts.
=> feat: setup repository dispatch for shell check

.github/workflows/artifact.yml
https://github.com/input-output-hk/partner-chains/actions/workflows/artifact.yml
=> feat: artifact.yml can optionally draft a release page and automatically attach assets

Cargo.lock, Cargo.toml, primitives/consensus/aura/Cargo.toml, primitives/consensus/aura/README.md, primitives/consensus/aura/src/block_proposal.rs, primitives/consensus/aura/src/inherent_digest.rs, primitives/consensus/aura/src/lib.rs
Please follow comments.
for you.
=> feat: add required primitives for custom Aura implementation

docs/user-guides/permissioned.md
Updated references to Cardano node to v9.1.1
=> Update node version number in permissioned.md

docs/user-guides/registered.md
Updated reference to Cardano node to v9.1.1
=> Update reference to Cardano node to v9.1.1 in registered.md

docs/user-guides/chain-builder.md
Updated second reference to version number of Cardano node.
=> Update 2nd reference to Cardano node to v9.1.1 in chain-builder.md

pallets/session-validator-management/src/lib.rs
Compiles correctly without the struct and impl being removed
=> chore: remove code that is not needed

.github/workflows/nix.yml, .github/workflows/sidechain-main-cli-binary-host.yml, changelog.md, cli/commands/src/lib.rs, cli/commands/src/pc_contracts_cli_params.rs, devnet/.envrc, docs/developer-guides/dependencies.md, flake.lock, flake.nix, nix/packages.nix, nix/shell.nix, partner-chains-cli/readme.md, partner-chains-cli/src/config.rs, partner-chains-cli/src/main.rs, partner-chains-cli/src/pc_contracts_cli_resources.rs, partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, partner-chains-cli/src/register/register3.rs, partner-chains-cli/src/setup_main_chain_state/mod.rs, partner-chains-cli/src/setup_main_chain_state/tests.rs, partner-chains-cli/src/smart_contracts.rs, primitives/authority-selection-inherents/src/tests.rs, primitives/chain-params/readme.md, primitives/domain/src/lib.rs, staging/.envrc
This coorelates with the renaming in
https://github.com/input-output-hk/partner-chains-smart-contracts/pull/113 please do not merge until that PR is in master, and the flake input is updated properly in this PR.
for you.
=> chore: rename sidechain-main-cli to pc-contracts-cli

runtime/src/lib.rs
=> Bump spec_version to 114

CONTRIBUTING.md
I was just reading the document when I came across the typo. this PR just fixes a small typo.
for you.
=> fix: Update CONTRIBUTING.md - small typo fix

dev/local-environment/configurations/pc-contracts-cli/entrypoint.sh, dev/local-environment/setup.sh
fixes:
- uses v1.1.0 release as default
- v1.1.1 draft release has been deleted and *_URL stopped working - artifacts were not downloaded
for you.
=> fix: make pc-demo great again

README.md
Just cleaning up a tiny formatting item so that the two smart contracts display correctly as sub-items a. and b. on lines 74 - 76.
=> Update README.md minor formatting item

dev/local-environment/configurations/pc-contracts-cli/entrypoint.sh, partner-chains-cli/src/deregister/mod.rs, partner-chains-cli/src/deregister/tests.rs, partner-chains-cli/src/main.rs
Tiny fixes for partner-chains-cli output of the deregister command
for you.
=> fix: minor typos in cli (ETCM-8471)

docs/developer-guides/native-token-migration-guide.md, pallets/native-token-management/README.md, primitives/native-token-management/README.md, primitives/native-token-management/src/lib.rs
This is the PR for native token documentation and migration strategy guide. 
It is based on changes from the following PRs:
* https://github.com/input-output-hk/partner-chains/pull/105 - handling observation only for selected versions of the runtime
* https://github.com/input-output-hk/partner-chains/pull/104 - handling the case when pallet is added post-genesis and historical transfers need to be loaded
* https://github.com/input-output-hk/partner-chains/pull/109 - making the main chain scripts optional, so their setting can start the observation
and describes how I see the migration strategy, assuming those changes.
You will need to get someone with write privileges.  Please contact IOG …
=> change: Native token documentation, migration strategy features and guide

docs/user-guides/registered.md
Adds 'deregistration' user-guide
=> Add deregister user documentation

Cargo.lock, Cargo.toml, changelog.md, node/Cargo.toml, node/src/rpc.rs, node/src/service.rs, primitives/sidechain-mc-hash/src/lib.rs, primitives/sidechain-slots/src/lib.rs, runtime/Cargo.toml
This updates dependency on polkadot-sdk to the newest stable version.
=> Update polkadot-sdk to polkadot-stable2409

mainchain-follower/db-sync-follower/src/block/mod.rs, mainchain-follower/db-sync-follower/src/candidates/cached.rs, mainchain-follower/db-sync-follower/src/candidates/mod.rs, mainchain-follower/db-sync-follower/src/candidates/tests.rs, mainchain-follower/db-sync-follower/src/native_token/mod.rs, mainchain-follower/main-chain-follower-cli/src/main.rs, mainchain-follower/mock/src/block.rs, mainchain-follower/mock/src/candidate.rs, node/src/main_chain_follower.rs
Made all data sources and mock data sources to be created using new/new_from_env and made the naming consistent
for you.
=> change: Reduce data source boilerplate in node

dev/local-environment/configurations/pc-contracts-cli/entrypoint.sh, dev/local-environment/setup.sh
Use v1.2.0 in pc-demo
for you.
=> Pc-demo-default-versions-bump

primitives/authority-selection-inherents/src/mock.rs, primitives/session-validator-management/query/src/lib.rs, primitives/session-validator-management/query/src/tests/mod.rs, primitives/session-validator-management/query/src/tests/runtime_api_mock.rs
Yeah, we somehow lost that one
for you.
=> fix: reconnect disconnected tests in session-validator-management-query crate

.github/actions/artifacts/generate-chain-specs/action.yml, node/src/staging.rs
=> Staging preview fixes

changelog.md, primitives/authority-selection-inherents/src/select_authorities.rs, runtime/src/lib.rs
https://input-output.atlassian.net/browse/ETCM-8674
Besides phrasing I've fixed the issue (that has happened in the past) that we long invalid number when `P+R` params are bigger than `MaxValidators`
for you.
=> fix: improve vague log message when selecting candidate

mainchain-follower/db-sync-follower/Cargo.toml, mainchain-follower/db-sync-follower/src/db_model.rs
=> fix: Individual db-sync-follower build

README.md, docs/developer-guides/native-token-migration-guide.md
Added Features section to README, and reorganized subsections. Added Native Token Management section, updated developer-guides for same.
=> docs: reorg README, updated docs for Native Token Management

docs/developer-guides/native-token-migration-guide.md
- fix typos
- move notes
- add process diagram
- add link to runtime upgrade guide
for you.
=> change: fix typos at native token migration guide

Cargo.lock, Cargo.toml, partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/offchain/Cargo.toml, toolkit/offchain/src/csl.rs, toolkit/offchain/src/lib.rs, toolkit/offchain/src/untyped_plutus.rs
This PR starts adding code that will be used for offchain part of smart contracts.
Part 1:
* applying params to script using `uplc`
* building CSL (cardano-serialization-lib) address for script
There is a test that checks the address of applied validator is the same as I obtain with current PureScript offchain code.
for you.
=> Add crate for the offchain code with basic required utils

.github/actions/tests/run-e2e-tests/action.yml, dev/local-environment/README.md
add: run pytest in multiple threads
for you.
=> add: run pytest in multiple threads

Cargo.lock, toolkit/offchain/Cargo.toml, toolkit/offchain/src/csl.rs
A subset of glue-code/coversions that was required to get deregister offchain code.
for you.
=> feat: add conversions from ogmios-client to CSL types

.github/actions/tests/local-environment-tests/action.yml
add: check if no skipped tests on last test run
for you.
=> add: check if no skipped tests on last test run

.github/actions/tests/run-e2e-tests/action.yml, .github/workflows/ci.yml
add: slack alerts for local env tests
for you.
=> add: slack alerts for local env tests

Cargo.lock, changelog.md, cli/commands/src/key_params.rs, docs/user-guides/registered.md, partner-chains-cli/Cargo.toml, partner-chains-cli/src/cardano_cli.rs, partner-chains-cli/src/cardano_key.rs, partner-chains-cli/src/config.rs, partner-chains-cli/src/main.rs, partner-chains-cli/src/ogmios/mod.rs, partner-chains-cli/src/pc_contracts_cli_resources.rs, partner-chains-cli/src/prepare_configuration/prepare_cardano_params.rs, partner-chains-cli/src/prepare_configuration/prepare_chain_params.rs, partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, partner-chains-cli/src/register/register1.rs, partner-chains-cli/src/register/register2.rs, partner-chains-cli/src/register/register3.rs, partner-chains-cli/src/tests/mod.rs, toolkit/offchain/src/csl.rs, utils/ogmios-client/src/types.rs
https://input-output.atlassian.net/browse/ETCM-8756
* Replaces using cardano-cli for address derivation with our offchain utilities
* Replaces using cardano-cli for querying address utxos  with ogmios-client
* Extracts parsing cardano key files from prepare-configuration and register2 into own module, to be used in register1 as well
Happy path:
```
./partner-chains-cli register1
⚙️ Registering as a committee candidate (step 1/3)
This wizard will query your UTXOs using address derived from the payment verification key and Ogmios service
> path to the payment verification file greg_payment.vkey
> Ogmios protocol (http/https) http
> Ogmios hostname localhost
> Ogmios port 1337
⚙️ Querying UTXOs of addr_test1vqezxrh24ts0775hulcg3ejcwj7hns8792vnn8met6z9gwsxt87zy from http://localhost:1337
? …
```
=> feat: do not use cardano-cli in from partner-chains-cli

.github/actions/tests/run-e2e-tests/action.yml, .gitignore
fix: slack alert on failed tests
for you.
=> fix: slack alert on failed tests

.github/actions/tests/run-e2e-tests/action.yml, .github/workflows/cd.yml
fix: wait for finalization with timeout
for you.
=> fix: wait for finalization with timeout

SECURITY.md
=> doc: add a SECURITY.md file

changelog.md, docker/sidechain-dependencies/docker-compose.yml, docs/user-guides/chain-builder.md, docs/user-guides/permissioned.md, docs/user-guides/registered.md, flake.lock, flake.nix, nix/shell.nix
Updates docker-compose, nix shell and docs with cardano-node 10.1.2
for you.
=> feat: Update cardano-node to be post Cheng#2 compatible

changelog.md, toolkit/offchain/src/collateral_selection.rs, toolkit/offchain/src/lib.rs
Adds Largest-First coin selection algorithm.
for you.
=> feat: Add Largest-First selection algorithm

flake.nix
=> fix: accept IFD and flake config by default

flake.lock, flake.nix, nix/packages/default.nix, nix/packages/ogmios.nix, nix/shell.nix
=> chore: update ogmios to 6.8.0

primitives/plutus-data/src/lib.rs, primitives/plutus-data/src/version_oracle.rs
Adds the version oracle datum minted by the `init-governance` transaction.
for you.
=> change: version oracle plutus data

nix/shell.nix
path was broken because the path changed in smart contracts.
for you.
=> fix: fix path to pc-contracts-cli

Cargo.lock, changelog.md, primitives/plutus-data/src/d_param.rs, primitives/plutus-data/src/permissioned_candidates.rs, toolkit/offchain/Cargo.toml, toolkit/offchain/src/csl.rs, toolkit/offchain/src/d_param.rs, toolkit/offchain/src/lib.rs, toolkit/offchain/src/permissioned_candidates.rs, toolkit/offchain/src/plutus_script.rs, utils/ogmios-client/src/query_ledger_state.rs, utils/ogmios-client/tests/query_ledger_state.rs
This is Part 1. D-parameter upsert - transaction that mints the token and stores on the chain. Transaction that updates d-param. Similar transactions for 
Part 2 will be using these transactions in a higher level function that uses Ogmios.
Part 3 will be wiring it into node commands and partner-chains-cli
for you.
=> D-parameter and permissioned candidates transactions offchain

changelog.md, dev/local-environment/setup.sh, docker/sidechain-dependencies/docker-compose.yml, docs/user-guides/chain-builder.md, docs/user-guides/registered.md, flake.lock, flake.nix, nix/packages/default.nix, nix/packages/ogmios.nix
Updates Ogmios dependencies v6.9.0
https://github.com/CardanoSolutions/ogmios/releases/tag/v6.9.0
for you.
=> feat: update ogmios to v6.9.0

Earthfile, dev/envs/devnet/.envrc, dev/envs/staging-preprod/.envrc, dev/envs/staging-preview/.envrc
=> fix: update address.json path in envrcs

dev/local-environment/setup.sh
Update of partner-chains-node and partner-chains-cli to v1.3.0 for local environment setup
https://github.com/input-output-hk/partner-chains/releases/tag/v1.3.0
for you.
=> chore: update node and cli version to v1.3.0 for local env

.github/workflows/staging.yml
=> chore: update test-plan for staging nightly

.github/workflows/devnet.yml, .github/workflows/staging.yml
=> bugfix: fix ctrf report

Cargo.lock, Cargo.toml, changelog.md, toolkit/offchain/src/csl.rs, toolkit/offchain/src/init_governance/tests.rs
Don't update minicbor because uplc lags behind.
to the issue.
~- [ ] New tests are added if needed and existing tests are updated.~
for you.
=> Update deps: pallas, uplc, cardano-serialization-lib. 

toolkit/offchain/src/csl.rs, toolkit/offchain/src/d_param.rs, toolkit/offchain/src/lib.rs, toolkit/offchain/src/permissioned_candidates.rs, toolkit/offchain/src/test_values.rs
Tokens should have been minted according to policy script, not the validator script.
This requires adding another parameter in few places to thread it.
for you.
=> fix: invalid tokens used in CSL common code

toolkit/offchain/src/csl.rs, toolkit/offchain/src/init_governance/tests.rs, toolkit/offchain/src/init_governance/transaction.rs
=> fix: correctly return native tokens in init-governance

.github/workflows/devnet.yml, .github/workflows/staging.yml
=> chore: set nightly tests to run on v1.3.0

toolkit/primitives/plutus-data/src/registered_candidates.rs
Adjusts the way we decode v0 of registration datum. own_pkh has been moved to the constant portion of the datum.
for you.
=> fix: decoding v0 register validator datum

Cargo.lock, Cargo.toml, changelog.md, flake.lock, toolkit/cli/node-commands/Cargo.toml, toolkit/cli/node-commands/src/lib.rs, toolkit/cli/smart-contracts-commands/Cargo.toml, toolkit/cli/smart-contracts-commands/src/init_governance.rs, toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/cli/smart-contracts-commands/src/main.rs, toolkit/offchain/Cargo.toml, toolkit/offchain/src/csl.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/init_governance/tests.rs, toolkit/offchain/src/lib.rs, toolkit/offchain/src/ogmios_mock.rs, toolkit/primitives/domain/src/lib.rs, toolkit/utils/ogmios-client/src/query_ledger_state.rs, toolkit/utils/ogmios-client/src/query_network.rs, toolkit/utils/ogmios-client/src/transactions.rs, toolkit/utils/ogmios-client/src/types.rs
* adds `run_init_governance` function that submits the transaction initializing on-chain governance
* adds a `partner-chains-smart-contracts-commands` crate used by the node to add smart contract-related commands
* adds first command `init-governance` 
for you.
=> change: init-governance command

flake.lock, toolkit/primitives/plutus-data/src/d_param.rs, toolkit/primitives/plutus-data/src/lib.rs, toolkit/primitives/plutus-data/src/permissioned_candidates.rs, toolkit/primitives/plutus-data/src/registered_candidates.rs
This transformation is required for implementing `register` command. It is also handy for `deregister` tests with trustworthy values
~- [ ] Any changes are noted in the `changelog.md` for affected crate~
for you.
=> feat: add transformation from RegisterValidatorDatum to PlutusData

Cargo.lock, toolkit/offchain/Cargo.toml, toolkit/offchain/src/csl.rs, toolkit/offchain/src/d_param.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/init_governance/tests.rs, toolkit/offchain/src/ogmios_mock.rs, toolkit/offchain/src/permissioned_candidates.rs, toolkit/offchain/src/scripts_data.rs, toolkit/offchain/src/test_values.rs, toolkit/utils/ogmios-client/src/types.rs
Uses mint or update d-param transactions.
~- [ ] Any changes are noted in the `changelog.md` for affected crate~
for you.
=> feat: upsert-d-parameter function

toolkit/offchain/Cargo.toml, toolkit/offchain/src/csl.rs, toolkit/offchain/src/d_param.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/permissioned_candidates.rs, toolkit/offchain/src/scripts_data.rs, toolkit/primitives/domain/src/lib.rs, toolkit/primitives/plutus-data/src/permissioned_candidates.rs
Upsert for permissioned candidates. Made very similar to D-parameter. One difference is that we should enforce comparision of candidates when they are sorted.
~- [ ] Any changes are noted in the `changelog.md` for affected crate~
for you.
=> Upsert permissioned-candidates function

.github/workflows/ci.yml
=> ci: test required check

node/runtime/src/lib.rs, toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/mainchain-follower/db-sync-follower/src/candidates/datum.rs, toolkit/mainchain-follower/main-chain-follower-cli/src/main.rs, toolkit/offchain/src/csl.rs, toolkit/offchain/src/init_governance/transaction.rs, toolkit/offchain/src/permissioned_candidates.rs, toolkit/offchain/src/plutus_script.rs, toolkit/partner-chains-cli/src/ogmios/mod.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_cardano_params.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/register/register2.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/mod.rs, toolkit/primitives/plutus-data/src/d_param.rs, toolkit/primitives/plutus-data/src/lib.rs, toolkit/primitives/plutus-data/src/permissioned_candidates.rs, toolkit/primitives/plutus-data/src/registered_candidates.rs, toolkit/primitives/sidechain-mc-hash/src/lib.rs, toolkit/utils/ogmios-client/src/types.rs
* Some Clippy fixes
* Increased our runtime spec to 140, so it is somehow similar to the coming release
for you.
=> chore: cargo clippy and node runtime update pre v1.4

docs/developer-guides/migration-guide-1.4.0.md
Migration guide for migrating from 1.3 to 1.4 (which includes upgrading smart contracts from from 6.2.2 to 7.0.0).
for you.
=> doc: 1.4.0 migration guide

node/runtime/src/mock.rs, res/bb-mock/default-registrations.json, toolkit/cli/commands/src/registration_signatures.rs, toolkit/mainchain-follower/db-sync-follower/src/candidates/mod.rs, toolkit/mainchain-follower/db-sync-follower/src/candidates/tests.rs, toolkit/mainchain-follower/mock/src/candidate.rs, toolkit/offchain/src/d_param.rs, toolkit/offchain/src/lib.rs, toolkit/offchain/src/register.rs, toolkit/offchain/src/test_values.rs, toolkit/partner-chains-cli/src/register/register1.rs, toolkit/partner-chains-cli/src/register/register2.rs, toolkit/primitives/authority-selection-inherents/src/filter_invalid_candidates.rs, toolkit/primitives/authority-selection-inherents/src/tests.rs, toolkit/primitives/domain/src/lib.rs, toolkit/primitives/plutus-data/src/registered_candidates.rs, toolkit/primitives/session-validator-management/query/src/tests/mock.rs
=> ETCM-8754: feat: implement register transaction

changelog.md
=> chore: update changelog with migration guide notice

E2E-tests/config/substrate/local_nodes.json, E2E-tests/tests/committee/test_blocks.py
test: xfail block author test
Refs: ETCM-8983
=> test: xfail block author test

docs/developer-guides/migration-guide-1.4.0.md
add clarifications to the guide for the following:
* SPO needs to run with their keystore present (and obviously preserve the keys)
* permissioned candidates should be copied from the old chain (get it with RPC or from the old file)
* the governance should have enough ADA
* `generate-keys` must be run before setting up the new chain
* keys file is needed for the registration
for you.
=> doc: Improve the 1.4.0 migration guide

.github/workflows/staging.yml, E2E-tests/config/substrate/staging_nodes.json
=> chore: prepare for v1.4.0 release

Cargo.lock, toolkit/offchain/src/test_values.rs, toolkit/utils/ogmios-client/Cargo.toml, toolkit/utils/ogmios-client/src/query_ledger_state.rs, toolkit/utils/ogmios-client/tests/query_ledger_state.rs
Adds reading the field `minFeeReferenceScripts` of `queryLedgerState/protocolParameters` response in Ogmios client.
for you.
=> add: min_fee_reference_scripts to Ogmis protocol parameters

dev/local-environment/README.md, dev/local-environment/configurations/cardano/entrypoint.sh, dev/local-environment/configurations/db-sync/entrypoint.sh, dev/local-environment/configurations/kupo/entrypoint.sh, dev/local-environment/configurations/ogmios/entrypoint.sh, dev/local-environment/configurations/partner-chains-nodes/partner-chains-node-1/entrypoint.sh, dev/local-environment/configurations/partner-chains-nodes/partner-chains-node-2/entrypoint.sh, dev/local-environment/configurations/partner-chains-nodes/partner-chains-node-3/entrypoint.sh, dev/local-environment/configurations/partner-chains-nodes/partner-chains-node-4/entrypoint.sh, dev/local-environment/configurations/partner-chains-nodes/partner-chains-node-5/entrypoint.sh, dev/local-environment/configurations/pc-contracts-cli/entrypoint.sh
* Fixes readme, replaces three cardano nodes with one
* decreases sleep times, increase is visible mostly when starting locally, ogmios is available much faster
for you.
=> Fix readme and decrease sleep times

Cargo.lock, toolkit/offchain/src/csl.rs, toolkit/offchain/src/d_param.rs, toolkit/offchain/src/d_param/mod.rs, toolkit/offchain/src/d_param/tests.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/plutus_script.rs, toolkit/offchain/src/scripts_data.rs, toolkit/utils/ogmios-client/Cargo.toml, toolkit/utils/ogmios-client/src/query_ledger_state.rs, toolkit/utils/ogmios-client/src/transactions.rs
Fixes the `upsert_d_param` transaction in the offchain code. Changes stolen form @jankun4 
for you.
=> fix: upsert-d-param transaction

changelog.md, toolkit/cli/smart-contracts-commands/src/d_parameter.rs, toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/offchain/src/d_param/mod.rs, toolkit/partner-chains-cli/src/cardano_key.rs, toolkit/partner-chains-cli/src/io.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/mod.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/tests.rs, toolkit/partner-chains-cli/src/tests/mod.rs, toolkit/primitives/domain/src/lib.rs
Adds upsert-d-param to `smart-contracts-commands`
[link](https://input-output.atlassian.net/browse/ETCM-8950)
to the issue.
for you.
=> Add upsert-d-parameter command

E2E-tests/tests/committee/test_registrations.py
test: improve log message on invalid registration
for you.
=> test: improve log message on invalid registration

Cargo.lock, Cargo.toml, toolkit/offchain/Cargo.toml, toolkit/offchain/tests/docker/entrypoint.sh, toolkit/offchain/tests/integration_tests.rs
Adds integration tests for:
* `init-goveranance`
* `upsert-d-parameter` - ignored, because it fails
* `registration` - ignored, because it fails
for you.
=> Add integration tests for smart-contracts

E2E-tests/config/substrate/devnet_nodes.json, E2E-tests/secrets/substrate/devnet/keys/governance_authority/init.skey.json
test: update e2e tests devnet config for v1.4.0
for you.
=> test: update e2e tests devnet config for v1.4.0

toolkit/partner-chains-cli/src/cardano_key.rs, toolkit/partner-chains-cli/src/deregister/mod.rs, toolkit/partner-chains-cli/src/deregister/tests.rs, toolkit/partner-chains-cli/src/io.rs, toolkit/partner-chains-cli/src/tests/mod.rs
=> ETCM-8753 use deregistration in wizard

toolkit/offchain/src/csl.rs, toolkit/offchain/src/register.rs, toolkit/offchain/src/reserve/init.rs, toolkit/offchain/src/scripts_data.rs, toolkit/offchain/src/test_values.rs
Adds transaction unit tests.
for you.
=> tests: implement unit test for transactions that initialize scripts

Cargo.lock, toolkit/cli/smart-contracts-commands/src/register.rs, toolkit/offchain/src/csl.rs, toolkit/offchain/src/register.rs, toolkit/partner-chains-cli/src/prepare_configuration/prepare_main_chain_config.rs, toolkit/partner-chains-cli/src/register/register3.rs, toolkit/primitives/domain/Cargo.toml, toolkit/primitives/domain/src/lib.rs
I introduced CSL as an optional dependency to the primitives crate in a previous PR. This PR moves code around to avoid this.
for you.
=> Remove CSL dependency from primitives

dev/local-environment/setup.sh
=> update setup cardano-node with 10.1.3 and db-sync

dev/envs/staging-preview/.envrc, dev/envs/staging-preview/addresses.json
Staging addresses and genesis uxto from 1.4.0 migration
for you.
=> chore: staging addresses after migration

Earthfile
Re: https://github.com/LukeMathWalker/cargo-chef/issues/290
Temporary workaround until this is resolved
=> fix: cargo-chef bug workaround

changelog.md, dev/docker/sidechain-dependencies/docker-compose.yml, dev/local-environment/setup.sh, dev/nix/packages/kupo.nix, dev/nix/packages/ogmios.nix, docs/user-guides/chain-builder.md, docs/user-guides/permissioned.md, docs/user-guides/registered.md, flake.lock, flake.nix, toolkit/offchain/tests/docker/Dockerfile, toolkit/offchain/tests/integration_tests.rs
Still to do:
* ~update SHAs of mac os containers~
* ~update our container in offchain integration tests~
=> chore: update 'stack' containers versions

changelog.md
docs: update changelog for 1.4.0
for you.
=> docs: update changelog for 1.4.0

toolkit/offchain/src/init_governance/transaction.rs, toolkit/offchain/src/reserve/mod.rs, toolkit/offchain/src/reserve/update_settings.rs, toolkit/offchain/src/update_governance/mod.rs, toolkit/offchain/tests/integration_tests.rs
This PR implements reserve settings update transaction.
for you.
=> ETCM-9064 reserve update settings transaction

toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/plutus_script.rs, toolkit/offchain/src/reserve/mod.rs, toolkit/offchain/src/scripts_data.rs, toolkit/utils/ogmios-client/src/types.rs
Adds Debug instances to some types, replaces derived instances for others, to avoid printing `Vec<u8>` or `[u8]` like a list of numbers.
=> feat: add and improve Debug for byte arrays and vectors

flake.lock, flake.nix
Updates omitted cardano-node in nix devshells
for you.
=> feat: update cardano-node in nix shells

docs/developer-guides/migration-guide-1.4.0.md
docs: fix typo in 1.4.0 migration guide
for you.
=> docs: fix typo in 1.4.0 migration guide

toolkit/primitives/plutus-data/src/reserve.rs
Fixes the bug introduced by https://github.com/input-output-hk/partner-chains/pull/357
for you.
=> fix: Add tests for ReserveDatum and fix decoding

toolkit/cli/smart-contracts-commands/src/reserve.rs, toolkit/offchain/src/reserve/create.rs, toolkit/offchain/src/reserve/deposit.rs, toolkit/offchain/src/reserve/update_settings.rs, toolkit/offchain/tests/integration_tests.rs, toolkit/primitives/domain/src/lib.rs, toolkit/primitives/plutus-data/src/reserve.rs
Removes support for Ada as a (Rewards) Reserve token
for you.
=> fix: remove support for Ada in smart-contracts reserve commands

docs/developer-guides/migration-guide-1.4.0.md
docs: fix migration guide public-keys filename
for you.
=> docs: fix migration guide public-keys filename

toolkit/offchain/tests/integration_tests.rs
Exposes test value for explicit use in tests
=> feat: expose hash of V-function from initial transaction

toolkit/offchain/src/csl.rs, toolkit/offchain/src/init_governance/transaction.rs, toolkit/offchain/src/register.rs, toolkit/offchain/src/reserve/create.rs, toolkit/offchain/src/reserve/deposit.rs, toolkit/offchain/src/reserve/init.rs
Some CSL helper functions, split out of my work on reserve-release. Mainly `TransactionOutputBuilder` extension to calculate minimum ADA
for you.
=> add: more helpers in csl.rs

.github/workflows/staging.yml
test: run nightly using v1.4.0-rc10
for you.
=> test: run nightly using v1.4.0-rc10

toolkit/cli/smart-contracts-commands/src/permissioned_candidates.rs, toolkit/cli/smart-contracts-commands/src/reserve.rs, toolkit/offchain/src/csl.rs, toolkit/offchain/src/reserve/create.rs, toolkit/offchain/src/reserve/deposit.rs, toolkit/offchain/src/reserve/handover.rs, toolkit/offchain/src/reserve/init.rs, toolkit/offchain/src/reserve/mod.rs, toolkit/offchain/tests/integration_tests.rs
Prepares code before adding "reserve handover" functionality, so the next PR will have less noise.
=> chore: prepare helpers for 'handover' transaction

toolkit/offchain/src/csl.rs, toolkit/offchain/src/plutus_script.rs, toolkit/offchain/src/reserve/create.rs, toolkit/offchain/src/reserve/deposit.rs, toolkit/primitives/domain/src/lib.rs
CSL helpers split out from https://github.com/input-output-hk/partner-chains/pull/373 and applied to other modules in offchain.
for you.
=> add: more CSL helpers in offchain code

changelog.md, toolkit/offchain/src/csl.rs, toolkit/offchain/src/reserve/handover.rs, toolkit/offchain/tests/integration_tests.rs
Transaction building and submission for handover reserve.
for you.
=> feat: implement transaction building for reserve handover

node/node/src/cli.rs
Replaces package name with generic environment parameter.
for you.
=> Updated package executable name to generic parameter

toolkit/offchain/src/csl.rs
=> ensure collateral is returned in tests

toolkit/offchain/src/csl.rs, toolkit/offchain/src/d_param/mod.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/init_governance/transaction.rs, toolkit/offchain/src/permissioned_candidates.rs, toolkit/offchain/src/plutus_script.rs, toolkit/offchain/src/reserve/deposit.rs, toolkit/offchain/src/reserve/init.rs, toolkit/offchain/src/reserve/mod.rs
- uses existing helpers where they weren't before
- adds some more helpers to make transaction logic cleaner
for you.
=> change: Offchain code cleanup

toolkit/offchain/src/reserve/deposit.rs, toolkit/offchain/src/reserve/handover.rs, toolkit/offchain/src/reserve/mod.rs, toolkit/offchain/src/reserve/release.rs, toolkit/offchain/src/reserve/update_settings.rs, toolkit/primitives/plutus-data/src/d_param.rs, toolkit/primitives/plutus-data/src/lib.rs, toolkit/primitives/plutus-data/src/permissioned_candidates.rs, toolkit/primitives/plutus-data/src/registered_candidates.rs, toolkit/primitives/plutus-data/src/reserve.rs
Some things that I stumbled upon and were distracting while trying to fix a datum encoding issue.
* type/variable renames
* use struct instead of tuple
for you.
=> misc cleanups

dev/local-environment/configurations/partner-chains-setup/entrypoint.sh, toolkit/cli/smart-contracts-commands/src/reserve.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/reserve/init.rs, toolkit/offchain/src/reserve/update_settings.rs, toolkit/offchain/tests/integration_tests.rs
=> chore: cleanup Option for the only parameter. Cleanup function unused in production code.

toolkit/offchain/src/csl.rs, toolkit/offchain/src/d_param/mod.rs, toolkit/offchain/src/d_param/tests.rs, toolkit/offchain/src/init_governance/mod.rs, toolkit/offchain/src/init_governance/tests.rs, toolkit/offchain/src/init_governance/transaction.rs, toolkit/offchain/src/permissioned_candidates.rs, toolkit/offchain/src/register.rs, toolkit/offchain/src/update_governance/mod.rs, toolkit/offchain/src/update_governance/test.rs, toolkit/utils/ogmios-client/src/jsonrpsee.rs
Cleanup ExCost calculation in init_governance, update_governance, d_param and permissioned_candidates.
for you.
=> ETCM-9222 cleanup ExCost calculation remaining commands

docs/developer-guides/native-token-reserve-management.md
Updates native tokens docs to use the new `partner-chains-node` cli.
for you.
=> ETCM-9287 update native tokens docs

docs/developer-guides/native-token-reserve-management.md, docs/user-guides/governance/governance.md
Adds documentation for users of Governance System
=> docs: write user documentation for Governance System

.github/workflows/devnet.yml, .github/workflows/staging.yml, e2e-tests/config/substrate/ci_stack.json, e2e-tests/config/substrate/devnet_nodes.json, e2e-tests/config/substrate/devnet_stack.json, e2e-tests/config/substrate/known_hosts, e2e-tests/config/substrate/staging_nodes.json, e2e-tests/config/substrate/staging_stack.json
setting staging for 1.5.0 tests
=> test: prepare staging for 1.5.0 e2e tests

.github/actions/release/create-draft-release/action.yml
ci: fix create-draft-release syntax
=> ci: fix create-draft-release syntax

toolkit/pallets/block-rewards/README.md, toolkit/pallets/block-rewards/src/lib.rs, toolkit/primitives/block-rewards/README.md, toolkit/primitives/block-rewards/src/lib.rs
=> doc: Document block rewards feature

e2e-tests/tests/conftest.py
=> test: fix collecting parametrized tests on epoch change

e2e-tests/config/substrate/staging_nodes.json
new staging deployment updates
=> test: update genesis-utxo on staging

toolkit/primitives/domain/src/lib.rs
=> fix: backward compatibility of MainchainSignature's coding

docs/developer-guides/native-token-reserve-management.md
These edits are only to make the document consistent with the IOG style guide for technical documents. No technical content has changed.
=> style guide edits only

.gitignore, dev/local-environment/configurations/cardano/entrypoint.sh, dev/local-environment/configurations/partner-chains-setup/entrypoint.sh, dev/local-environment/envrc, dev/local-environment/modules/cardano.txt, dev/local-environment/setup.sh
Mounts the shared directory of the local env to a directory accessible from host and adds an `envrc` file that can be sourced to load the custom Cardano and PC parameters.
for you.
=> add: envrc file exposing local environment parameters

Cargo.lock, Cargo.toml, node/node/Cargo.toml, toolkit/mainchain-follower/db-sync-follower/Cargo.toml, toolkit/mainchain-follower/db-sync-follower/src/db_model.rs, toolkit/mainchain-follower/db-sync-follower/src/lib.rs, toolkit/mainchain-follower/db-sync-follower/src/stake_distribution/mod.rs, toolkit/mainchain-follower/db-sync-follower/src/stake_distribution/tests.rs, toolkit/mainchain-follower/db-sync-follower/testdata/stake-distribution/migrations/1_create_schema.sql, toolkit/mainchain-follower/db-sync-follower/testdata/stake-distribution/migrations/2_data.sql, toolkit/mainchain-follower/mock/Cargo.toml, toolkit/primitives/domain/src/lib.rs, toolkit/primitives/stake-distribution/Cargo.toml, toolkit/primitives/stake-distribution/src/lib.rs
Implements stake distribution query.
for you.
=> ETCM-9305 stake distribution query

.github/workflows/staging.yml, e2e-tests/config/substrate/staging_nodes.json
chore: run staging e2e tests from proper tag
=> chore: run staging e2e tests from proper tag

docs/user-guides/chain-builder.md
=> Fix broken links

dev/nix/shell.nix
This PR restricts the fix introduced in #516 to only be applied on linux as it broke the mac build.
for you.
=> Fix jemalloc on darwin

dev/nix/shell.nix
Provide python 3.12 in the nix shell (previously we were on 3.11)
for you.
=> Update python to 3.12

e2e-tests/src/blockchain_api.py
test: improve address association docstring
=> test: improve address association docstring

toolkit/pallets/block-production-log/src/lib.rs, toolkit/pallets/block-production-log/src/test.rs
Small optimization for `drop_prefix`
for you.
=> Small optimization

docs/user-guides/chain-builder.md, docs/user-guides/permissioned.md, docs/user-guides/registered.md
Clean up docs version notes, specify which key is needed for SPO registration.
~~- [ ] CI passes. See note on CI.~~
for you.
=> docs: version note updates

changelog.md, toolkit/offchain/src/csl.rs, toolkit/offchain/src/reserve/deposit.rs, toolkit/offchain/src/reserve/handover.rs, toolkit/offchain/src/reserve/release.rs, toolkit/offchain/tests/integration_tests.rs
* Fixes error when trying to release all tokens of reserve
* When previous one got fixed, it turned out that our `handover` fails if there are no tokens in reserve
https://input-output.atlassian.net/browse/ETCM-9498
=> fix: allow release all tokens and handover of zero tokens

e2e-tests/pytest.ini, e2e-tests/src/blockchain_api.py, e2e-tests/src/substrate_api.py, e2e-tests/tests/committee/test_blocks.py, e2e-tests/tests/committee/test_registrations.py
E2E test for block-production-log pallet.
for you.
=> ETCM-9394: e2e test for block-production-log pallet

e2e-tests/config/substrate/staging_nodes.json
Update the deployment and initial PC epoch values in the 
staging_nodes.json configuration file to reflect the latest 
deployment with wipe
=> test(config): update staging config after deployment

dev/local-environment/configurations/wizard/governance-authority/entrypoint.sh, dev/local-environment/configurations/wizard/registered/entrypoint.sh
fixed:
- correct the expected prompt for the payment signing key file
- remove unnecessary prompts related to the Ogmios protocol
added:
- set initial funds for Alice and sudo in local-env -d 5 (wizard deployment)
Refs: ETCM-8256
=> chore: update local-env wizards commands and set sudo

Cargo.lock, Cargo.toml, toolkit/offchain/src/csl.rs, toolkit/offchain/src/governance.rs
* fix incomplete transformation to CSL TransactionOutput
* remove unnecessary unwrap
* update CSL version
=> feat: improvements around using CSL

.github/workflows/ci.yml, e2e-tests/config/substrate/ci_nodes.json, e2e-tests/secrets/substrate/ci/ci-ci.json, e2e-tests/tests/conftest.py
Python is not being set up in ci-review before e2e tests are being run.
=> ETCM-9501 fix python setup

e2e-tests/tests/committee/test_blocks.py
Removes E2E test for pallet removed in #564
=> ETCM-9577 remove old block rewards e2e test

toolkit/cli/smart-contracts-commands/src/assemble_tx.rs, toolkit/cli/smart-contracts-commands/src/lib.rs, toolkit/offchain/src/assemble_tx.rs, toolkit/offchain/src/csl.rs, toolkit/offchain/src/lib.rs, toolkit/primitives/domain/src/lib.rs
[link](https://input-output.atlassian.net/browse/ETCM-9519)
=> add assemble-tx command

.github/workflows/ci.yml, .github/workflows/staging.yml, dev/envs/ci-preview/.envrc, dev/envs/ci-preview/addresses.json, e2e-tests/config/substrate/ci_nodes.json
fixes:
- ci-preview env was using staging's addresses and was impacting nightly tests; I initialized separate chain for ci
=> tests: set new chain for ci-preview

toolkit/offchain/tests/integration_tests.rs
Proves that it works for upsert-permissioned-candidates.
REF: ETCM-9500
=> test: adds MultiSig governance use in integration tests, 

toolkit/block-participation/primitives/src/lib.rs, toolkit/block-participation/primitives/src/tests.rs, toolkit/cli/commands/src/block_producer_metadata_signatures.rs, toolkit/committee-selection/authority-selection-inherents/src/filter_invalid_candidates.rs, toolkit/committee-selection/authority-selection-inherents/src/mock.rs, toolkit/committee-selection/selection/src/ariadne.rs, toolkit/mainchain-follower/db-sync-follower/src/stake_distribution/mod.rs, toolkit/native-token-management/primitives/src/tests/mod.rs, toolkit/partner-chains-cli/src/generate_keys/tests.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
Some `cargo clippy` suggestions executed with predefined rules from main `Cargo.toml`
=> Apply clippy suggestions

e2e-tests/src/substrate_api.py
fixes:
- `test_permissioned_candidates.py` would fail on a chain which has not set candidates yet
=> test(fix): test_permissioned_candidates was failing if list was not set

Cargo.lock, Cargo.toml, node/node/Cargo.toml, node/node/src/rpc.rs, node/runtime/Cargo.toml, node/runtime/src/lib.rs, toolkit/block-producer-metadata/primitives/Cargo.toml, toolkit/block-producer-metadata/primitives/src/lib.rs, toolkit/block-producer-metadata/rpc/Cargo.toml, toolkit/block-producer-metadata/rpc/src/lib.rs, toolkit/sidechain/domain/src/byte_string.rs, toolkit/sidechain/domain/src/lib.rs, toolkit/sidechain/rpc/Cargo.toml
RPC for block producer metadata pallet
=> ETCM-9598 block producer metadata rpc

toolkit/sidechain/sidechain-block-search/src/impl_find_block.rs
[link](https://input-output.atlassian.net/browse/ETCM-8439)
=> improve the error message when block cannot be found

docs/developer-guides/block-participation-rewards.md
Adds a guide on how to implement a complete block participation reward payouts mechanism using Partner Chains SDK components.
ref: ETCM-9650
=> docs: ETCM-9650 delegator rewards how-to

README.md, docs/developer-guides/block-participation-rewards.md
=> docs: block-participation-rewards

.github/workflows/staging.yml
=> chore: bump staging nightly branch and test plan

changelog.md, toolkit/block-production-log/primitives/src/lib.rs, toolkit/committee-selection/selection/src/ariadne_v2.rs, toolkit/committee-selection/selection/src/lib.rs
This adds an algorithm that has less variance but the same expected values as currently used ariadne.
See this doc: https://input-output.atlassian.net/wiki/spaces/SID/pages/4642832385/Ariadne+V2+-+minimal+variance+selection+algorithm
=> feat: add selection algorithm with guaranteed seats

Cargo.lock, Cargo.toml, demo/runtime/src/lib.rs, toolkit/governed-map/pallet/Cargo.toml, toolkit/governed-map/pallet/src/lib.rs, toolkit/governed-map/pallet/src/mock.rs, toolkit/governed-map/pallet/src/tests.rs, toolkit/governed-map/primitives/Cargo.toml, toolkit/governed-map/primitives/src/lib.rs, toolkit/sidechain/domain/Cargo.toml, toolkit/sidechain/domain/src/byte_string.rs, toolkit/sidechain/domain/src/lib.rs
Adds the pallet for Governed Map. This PR does not contain the hooks for reacting to changes to the data in the map, because I need to think them through.
=> add: ETCM-8633 Governed Map pallet

toolkit/block-producer-metadata/rpc/Cargo.toml, toolkit/cli/commands/Cargo.toml, toolkit/cli/node-commands/Cargo.toml, toolkit/committee-selection/query/Cargo.toml, toolkit/committee-selection/rpc/Cargo.toml, toolkit/data-sources/db-sync/Cargo.toml, toolkit/partner-chains-cli/Cargo.toml, toolkit/sidechain/rpc/Cargo.toml, toolkit/sidechain/sidechain-block-search/Cargo.toml, toolkit/smart-contracts/plutus-data/Cargo.toml
Removes unnecessary use of default features from workspace crates.
=> remove: No default features in dependencies

changelog.md
=> doc: mark removal of block-rewards pallet as breaking change

Cargo.lock, demo/node/Cargo.toml, toolkit/data-sources/db-sync/Cargo.toml, toolkit/data-sources/db-sync/src/db_model.rs, toolkit/data-sources/db-sync/src/governed_map/mod.rs, toolkit/data-sources/db-sync/src/governed_map/tests.rs, toolkit/data-sources/db-sync/src/lib.rs, toolkit/data-sources/db-sync/testdata/governed-map/migrations/1_create_schema.sql, toolkit/data-sources/db-sync/testdata/governed-map/migrations/2_data.sql, toolkit/data-sources/mock/Cargo.toml, toolkit/data-sources/mock/src/governed_map.rs, toolkit/data-sources/mock/src/lib.rs, toolkit/utils/db-sync-sqlx/src/lib.rs
This PR adds data source and query for governed map
=> ETCM-9703 governed map data source

e2e-tests/config/config.json, e2e-tests/src/blockchain_api.py, e2e-tests/src/db/models.py, e2e-tests/tests/committee/conftest.py, e2e-tests/tests/committee/test_committee.py
added:
- guaranteed seats tests
- seats distribution matching DParam tests
changed:
- participation tolerance will use absolute value if calculated one is too small
Refs: ETCM-8934
=> test: add ariadne v2 tests

e2e-tests/tests/committee/test_committee.py
fixes:
- post-merge CI failing due to unknown stake on MC epoch 2
=> test: fix post-merge CI

toolkit/smart-contracts/commands/src/governed_map.rs, toolkit/smart-contracts/offchain/src/governed_map/mod.rs, toolkit/smart-contracts/offchain/src/governed_map/tests.rs, toolkit/smart-contracts/offchain/src/permissioned_candidates.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
Adds update command for governed map
=> ETCM-9695 governed map - update command

.github/pull_request_template.md
=> change: add documentation to the PR checklist

toolkit/smart-contracts/commands/src/governed_map.rs, toolkit/smart-contracts/offchain/src/governed_map/mod.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
* Rearranges governed map operations to make more sense, both in the code and the help text. (Split to separate commit for easier review.)
* Adds missing help for arguments.
* Removes debug printing and printing of entry values from logs/errors. As entries can be potentially quite large it's better to leave to the user to query them if needed.
* Makes integration tests shorter and adds another check in the test for update.
=> Tidy up governed map implementation

README.md, docs/intro.md
This is an attempt to overhaul our README making it look a bit more professional and nicer.
**Notes** 
- This is just a first step - obviously we'll need to do some more work still
- I reused some content from the old docs repository
- I intentionally dropped the guides - those really need to be redone
=> revamp project README

README.md
=> README: fix TOC

.github/actions/tests/doc-tests/action.yaml, .github/workflows/ci.yml, README.md
For now this only adds a check to compare the polkadot-sdk version in README with the one from Cargo.toml - Going forward, and as we continue with documentation efforts this should grow and expand
=> Add doc tests

toolkit/address-associations/pallet/src/lib.rs
Adds missing documentation for public members and makes docs mandatory in the crate
=> doc: ETCM-9687 Document address associations pallet

README.md
Mentions that parts our the code here are under GPLv3 with classpath exception
=> Mention parts of code with GPLv3 with classpath exception

toolkit/smart-contracts/commands/src/governed_map.rs
Old result:
```json
[
{"key":"abc", "value":"0x1"},
{"key":"def", "value":"0x2"}
]
```
New result:
```json
{
"abc": "0x1",
"def": "0x2"
}
```
=> change: Return a json object from governed map list command

toolkit/block-participation/pallet/Cargo.toml, toolkit/block-participation/pallet/src/lib.rs, toolkit/block-participation/primitives/src/lib.rs
- documents the block participation crates and makes docs mandatory
- makes some fields intended to be user-facing public
=> docs: ETCM-9687 block participation feature docs

demo/runtime/src/lib.rs, e2e-tests/src/partner_chain_rpc.py, toolkit/block-producer-metadata/pallet/src/benchmarking.rs, toolkit/block-producer-metadata/pallet/src/lib.rs, toolkit/block-producer-metadata/pallet/src/mock.rs, toolkit/block-producer-metadata/rpc/src/lib.rs
=> doc: ETCM-9687 Block Producer Metadata feature documentation

toolkit/block-production-log/pallet/README.md, toolkit/block-production-log/pallet/src/benchmarking.rs, toolkit/block-production-log/pallet/src/lib.rs, toolkit/block-production-log/pallet/src/mock.rs, toolkit/block-production-log/primitives/src/lib.rs
Adds docs for block production log feature
=> ETCM-9687 block production log docs

demo/node/src/data_sources.rs, toolkit/data-sources/db-sync/src/governed_map/mod.rs, toolkit/data-sources/db-sync/src/governed_map/tests.rs, toolkit/governed-map/primitives/src/lib.rs
replaces the mock data source in the demo node
=> fix: use production data source in demo node

README.md, docs/intro.md
Provide links to our rust-docs in both the README and in docs/intro.md
=> Add links to the rust-docs to README.md and docs/intro.md

toolkit/governed-map/README.md, toolkit/governed-map/pallet/src/benchmarking.rs, toolkit/governed-map/pallet/src/lib.rs, toolkit/sidechain/domain/src/byte_string.rs
=> doc: ETCM-9687 Governed Map pallet docs

demo/node/src/staging.rs, demo/node/src/template_chain_spec.rs, demo/node/src/testnet.rs, demo/runtime/src/genesis_config_presets.rs, toolkit/governed-map/pallet/src/lib.rs, toolkit/governed-map/primitives/src/lib.rs
- Expands documentation on the data size limits
- Adds section on updating the main chain scripts
=> docs: ETCM-9819 Improve Governed Map pallet docs

demo/runtime/src/lib.rs, toolkit/committee-selection/pallet/src/lib.rs, toolkit/committee-selection/pallet/src/tests.rs
=> chore: Remove redundant getters from committee selection pallet

demo/runtime/src/lib.rs, toolkit/sidechain/domain/src/byte_string.rs, toolkit/sidechain/domain/src/crypto.rs, toolkit/sidechain/domain/src/lib.rs, toolkit/sidechain/domain/src/mainchain_epoch.rs, toolkit/utils/byte-string-derivation/src/lib.rs
=> doc: ETCM-9687 Domain crate documentation

toolkit/committee-selection/authority-selection-inherents/src/ariadne_inherent_data_provider.rs, toolkit/committee-selection/authority-selection-inherents/src/authority_selection_inputs.rs, toolkit/committee-selection/authority-selection-inherents/src/filter_invalid_candidates.rs, toolkit/committee-selection/authority-selection-inherents/src/lib.rs, toolkit/committee-selection/authority-selection-inherents/src/mock.rs, toolkit/committee-selection/authority-selection-inherents/src/select_authorities.rs, toolkit/governed-map/primitives/src/lib.rs, toolkit/sidechain/domain/src/lib.rs, toolkit/sidechain/sidechain-mc-hash/src/lib.rs
=> docs: ETCM-9687 add docs for authority selection inherents

e2e-tests/secrets/substrate/local/local.json, e2e-tests/src/blockchain_api.py, e2e-tests/src/substrate_api.py, e2e-tests/tests/conftest.py, e2e-tests/tests/governed_map/conftest.py, e2e-tests/tests/governed_map/smart_contracts/test_get_insert_remove.py, e2e-tests/tests/governed_map/smart_contracts/test_update.py, e2e-tests/tests/governed_map/test_observability.py
=> tests: added GovernedMap observability tests

toolkit/sidechain/sidechain-mc-hash/src/lib.rs
=> doc: ETCM-9687 document the main chain reference hash feature

docs/intro.md
Small addition to docs/intro.md providing info on pc runtime dependencies. I try to make small incremental improvements to the docs. Please have a look. The file should gradually replace the guides we have. 
The idea is to provide some relevant information on those externals but mostly refer to the respective existing documentation. We cannot explain details of how to run cardano-node or db-sync.
**But** if there are any particularities about how cardano-node needs to be run or any way in which db-sync needs to be configured that is out-of-the-ordinary and specific to PC it would be great to add it here. Please comment if you can think of something :)
=> docs: Add section on running pc dependencies

changelog.md, docs/user-guides/governance/governance.md
=> docs: governed-map

toolkit/sidechain/sidechain-slots/src/lib.rs, toolkit/sidechain/sidechain-slots/src/runtime_api_client.rs
=> docs: ETCM-9687 sidechain-slots crate docs

Cargo.lock, toolkit/committee-selection/query/src/types/registrations.rs, toolkit/smart-contracts/offchain/src/reserve/create.rs, toolkit/smart-contracts/offchain/src/reserve/release.rs, toolkit/smart-contracts/offchain/src/reserve/update_settings.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs, toolkit/smart-contracts/plutus-data/Cargo.toml, toolkit/smart-contracts/plutus-data/src/d_param.rs, toolkit/smart-contracts/plutus-data/src/governed_map.rs, toolkit/smart-contracts/plutus-data/src/lib.rs, toolkit/smart-contracts/plutus-data/src/permissioned_candidates.rs, toolkit/smart-contracts/plutus-data/src/registered_candidates.rs, toolkit/smart-contracts/plutus-data/src/reserve.rs, toolkit/smart-contracts/plutus-data/src/version_oracle.rs
=> docs: ETCM-9687 add smart-contracts/plutus-data docs

toolkit/sidechain/domain/src/byte_string.rs
Custom implementation of Decode trait to ensure that type has valid UTF-8 characters.
Associated with https://github.com/input-output-hk/partner-chains/pull/745#discussion_r2075883458 and https://github.com/input-output-hk/partner-chains/pull/622
=> Custom Decode for BoundedString

toolkit/sidechain/pallet/src/lib.rs
=> docs: ETCM-9687 Sidechain pallet docs

.github/actions/tests/argocd-tests/action.yml, .github/workflows/release.yml, e2e-tests/pytest.ini, e2e-tests/tests/committee/conftest.py, e2e-tests/tests/committee/test_blocks.py, e2e-tests/tests/committee/test_committee.py, e2e-tests/tests/committee/test_permissioned_registrations.py, e2e-tests/tests/committee/test_registrations.py, e2e-tests/tests/delegator_rewards/test_block_production_log.py, e2e-tests/tests/test_rpc.py, e2e-tests/tests/test_smoke.py
see `pytest.ini` to get overview of supported tags
=> tests(chore): clean up tags

e2e-tests/src/substrate_api.py
fixes:
- (race condition) governed map observability tests could fail if partner chains node created a block referencing stable main chain block just after main has created <security_param + 1> block
=> tests(fix): observe mc reference block to stop subscription

demo/node/Cargo.toml, toolkit/sidechain/primitives/src/lib.rs, toolkit/sidechain/rpc/Cargo.toml, toolkit/sidechain/rpc/src/lib.rs, toolkit/sidechain/rpc/src/types/mod.rs, toolkit/sidechain/rpc/src/types/sidechain.rs, toolkit/sidechain/sidechain-block-search/src/binary_search.rs, toolkit/sidechain/sidechain-block-search/src/lib.rs
=> doc: ETCM-9687 more sidechain crate docs

docs/intro.md
Clarify the dependency on ogmios for Validators
=> docs: clarify ogmios use

demo/node/src/staging.rs, demo/node/src/template_chain_spec.rs, demo/node/src/testnet.rs, toolkit/native-token-management/pallet/src/benchmarking.rs, toolkit/native-token-management/pallet/src/lib.rs, toolkit/native-token-management/pallet/src/mock.rs, toolkit/native-token-management/primitives/src/lib.rs
- documents the primitives and pallet crate for native token management feature
- fixes visibility of some components
- makes the initial main chain scripts in the genesis config optional
=> change: ETCM-9687 docs and small fixes for native token crates

toolkit/partner-chains-cli/src/prepare_configuration/init_governance.rs, toolkit/partner-chains-cli/src/setup_main_chain_state/mod.rs, toolkit/smart-contracts/commands/src/assemble_tx.rs, toolkit/smart-contracts/offchain/src/assemble_and_submit_tx.rs, toolkit/smart-contracts/offchain/src/assemble_tx.rs, toolkit/smart-contracts/offchain/src/await_tx.rs, toolkit/smart-contracts/offchain/src/cardano_keys.rs, toolkit/smart-contracts/offchain/src/csl.rs, toolkit/smart-contracts/offchain/src/d_param/mod.rs, toolkit/smart-contracts/offchain/src/governance.rs, toolkit/smart-contracts/offchain/src/governed_map/mod.rs, toolkit/smart-contracts/offchain/src/init_governance/mod.rs, toolkit/smart-contracts/offchain/src/lib.rs, toolkit/smart-contracts/offchain/src/multisig.rs, toolkit/smart-contracts/offchain/src/permissioned_candidates.rs, toolkit/smart-contracts/offchain/src/plutus_script.rs, toolkit/smart-contracts/offchain/src/register.rs, toolkit/smart-contracts/offchain/src/reserve/create.rs, toolkit/smart-contracts/offchain/src/reserve/init.rs, toolkit/smart-contracts/offchain/src/reserve/mod.rs, toolkit/smart-contracts/offchain/src/reserve/release.rs, toolkit/smart-contracts/offchain/src/reserve/update_settings.rs, toolkit/smart-contracts/offchain/src/scripts_data.rs, toolkit/smart-contracts/offchain/src/update_governance/mod.rs, toolkit/smart-contracts/offchain/tests/integration_tests.rs
=> change: ETCM-9687 document smart-contracts/offchain

docs/intro.md, docs/user-guides/manual-setup.md, toolkit/smart-contracts/commands/readme.md, toolkit/smart-contracts/commands/src/governance.rs
Quite short documentation, but it relies heavily on already existing and TBD docs.
In other words I try to avoid repetitions here.
=> docs: setup without wizards

toolkit/data-sources/db-sync/src/lib.rs
Doumenting option our toolkit relies on
=> docs: db-sync insert.options.plutus must be enable

Cargo.lock, Cargo.toml, toolkit/cli/commands/src/address_association_signatures.rs, toolkit/cli/node-commands/Cargo.toml, toolkit/cli/node-commands/src/lib.rs, toolkit/partner-chains-cli/src/config.rs, toolkit/partner-chains-cli/src/generate_keys/mod.rs, toolkit/partner-chains-cli/src/io.rs, toolkit/partner-chains-cli/src/lib.rs, toolkit/partner-chains-cli/src/runtime_bindings.rs, toolkit/partner-chains-cli/src/tests/config.rs, toolkit/partner-chains-cli/src/tests/mod.rs
=> docs: ETCM-9687: document partner-chains-cli

toolkit/cli/node-commands/src/lib.rs
=> docs: ETCM-9687: document cli/node-commands

Cargo.lock, Cargo.toml, toolkit/committee-selection/selection-simulator/Cargo.toml, toolkit/committee-selection/selection-simulator/README.md, toolkit/committee-selection/selection-simulator/src/analyze.rs, toolkit/committee-selection/selection-simulator/src/main.rs, toolkit/committee-selection/selection-simulator/src/simple_sim.rs
=> [testing] tool for simulating Ariadne

toolkit/partner-chains-cli/src/config.rs, toolkit/partner-chains-cli/src/register/register1.rs
=> change: ETCM-9838 Include file path in missing keystore error

Dockerfile, dev/docker/runner.Dockerfile, dev/local-environment-dynamic/configurations/partner-chains-setup/entrypoint.sh, dev/local-environment/configurations/partner-chains-setup/entrypoint.sh, dev/local-environment/configurations/wizard/governance-authority/entrypoint.sh, dev/local-environment/configurations/wizard/permissioned/entrypoint.sh, dev/local-environment/configurations/wizard/registered/entrypoint.sh
Moved installation of some dependencies from entrypoints in local-environment to Dockerfile of the image that is used
=> Do not install dependencies in entrypoints

toolkit/sidechain/domain/src/lib.rs
Moves tests to the bottom of the file.
Removes parentheses around type definition - should remove warning that causes PR close job to fail.
=> refactor: move tests to the bottom of the file, remove redundant parentheses

Cargo.lock, Cargo.toml, toolkit/smart-contracts/offchain/src/scripts_data.rs
=> chore: upgrade raw-crates to 8.1.0

toolkit/smart-contracts/offchain/src/d_param/mod.rs, toolkit/smart-contracts/offchain/src/permissioned_candidates.rs
Throws an error if more than 1 DParam or Permissioned Candidates UTxOs are found. Discards all UTxOs without the proper token attached.
[link](https://input-output.atlassian.net/browse/ETCM-12352)
=> fix trash utxo d-param and p-candidates error
